// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: open_space_roi_decider_config.proto
// </auto-generated>

#pragma warning disable 0612, 1591, 3021
namespace apollo.planning
{

    [global::ProtoBuf.ProtoContract()]
    public partial class OpenSpaceRoiDeciderConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public OpenSpaceRoiDeciderConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(10)]
        public double roi_longitudinal_range
        {
            get { return __pbn__roi_longitudinal_range ?? 10; }
            set { __pbn__roi_longitudinal_range = value; }
        }
        public bool ShouldSerializeroi_longitudinal_range()
        {
            return __pbn__roi_longitudinal_range != null;
        }
        public void Resetroi_longitudinal_range()
        {
            __pbn__roi_longitudinal_range = null;
        }
        private double? __pbn__roi_longitudinal_range;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(7)]
        public double parking_start_range
        {
            get { return __pbn__parking_start_range ?? 7; }
            set { __pbn__parking_start_range = value; }
        }
        public bool ShouldSerializeparking_start_range()
        {
            return __pbn__parking_start_range != null;
        }
        public void Resetparking_start_range()
        {
            __pbn__parking_start_range = null;
        }
        private double? __pbn__parking_start_range;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool parking_inwards
        {
            get { return __pbn__parking_inwards ?? false; }
            set { __pbn__parking_inwards = value; }
        }
        public bool ShouldSerializeparking_inwards()
        {
            return __pbn__parking_inwards != null;
        }
        public void Resetparking_inwards()
        {
            __pbn__parking_inwards = null;
        }
        private bool? __pbn__parking_inwards;

        [global::ProtoBuf.ProtoMember(4)]
        public bool enable_perception_obstacles
        {
            get { return __pbn__enable_perception_obstacles.GetValueOrDefault(); }
            set { __pbn__enable_perception_obstacles = value; }
        }
        public bool ShouldSerializeenable_perception_obstacles()
        {
            return __pbn__enable_perception_obstacles != null;
        }
        public void Resetenable_perception_obstacles()
        {
            __pbn__enable_perception_obstacles = null;
        }
        private bool? __pbn__enable_perception_obstacles;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue(0.1)]
        public double parking_depth_buffer
        {
            get { return __pbn__parking_depth_buffer ?? 0.1; }
            set { __pbn__parking_depth_buffer = value; }
        }
        public bool ShouldSerializeparking_depth_buffer()
        {
            return __pbn__parking_depth_buffer != null;
        }
        public void Resetparking_depth_buffer()
        {
            __pbn__parking_depth_buffer = null;
        }
        private double? __pbn__parking_depth_buffer;

    }

}

#pragma warning restore 0612, 1591, 3021
