// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: control_cmd.proto

#pragma warning disable 0612, 1591, 3021
namespace apollo.control
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LatencyStats : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public LatencyStats()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public double total_time_ms
        {
            get { return __pbn__total_time_ms.GetValueOrDefault(); }
            set { __pbn__total_time_ms = value; }
        }
        public bool ShouldSerializetotal_time_ms()
        {
            return __pbn__total_time_ms != null;
        }
        public void Resettotal_time_ms()
        {
            __pbn__total_time_ms = null;
        }
        private double? __pbn__total_time_ms;

        [global::ProtoBuf.ProtoMember(2)]
        public double[] controller_time_ms { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public bool total_time_exceeded
        {
            get { return __pbn__total_time_exceeded.GetValueOrDefault(); }
            set { __pbn__total_time_exceeded = value; }
        }
        public bool ShouldSerializetotal_time_exceeded()
        {
            return __pbn__total_time_exceeded != null;
        }
        public void Resettotal_time_exceeded()
        {
            __pbn__total_time_exceeded = null;
        }
        private bool? __pbn__total_time_exceeded;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ControlCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ControlCommand()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::apollo.common.Header header { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public double throttle
        {
            get { return __pbn__throttle.GetValueOrDefault(); }
            set { __pbn__throttle = value; }
        }
        public bool ShouldSerializethrottle()
        {
            return __pbn__throttle != null;
        }
        public void Resetthrottle()
        {
            __pbn__throttle = null;
        }
        private double? __pbn__throttle;

        [global::ProtoBuf.ProtoMember(4)]
        public double brake
        {
            get { return __pbn__brake.GetValueOrDefault(); }
            set { __pbn__brake = value; }
        }
        public bool ShouldSerializebrake()
        {
            return __pbn__brake != null;
        }
        public void Resetbrake()
        {
            __pbn__brake = null;
        }
        private double? __pbn__brake;

        [global::ProtoBuf.ProtoMember(6)]
        public double steering_rate
        {
            get { return __pbn__steering_rate.GetValueOrDefault(); }
            set { __pbn__steering_rate = value; }
        }
        public bool ShouldSerializesteering_rate()
        {
            return __pbn__steering_rate != null;
        }
        public void Resetsteering_rate()
        {
            __pbn__steering_rate = null;
        }
        private double? __pbn__steering_rate;

        [global::ProtoBuf.ProtoMember(7)]
        public double steering_target
        {
            get { return __pbn__steering_target.GetValueOrDefault(); }
            set { __pbn__steering_target = value; }
        }
        public bool ShouldSerializesteering_target()
        {
            return __pbn__steering_target != null;
        }
        public void Resetsteering_target()
        {
            __pbn__steering_target = null;
        }
        private double? __pbn__steering_target;

        [global::ProtoBuf.ProtoMember(8)]
        public bool parking_brake
        {
            get { return __pbn__parking_brake.GetValueOrDefault(); }
            set { __pbn__parking_brake = value; }
        }
        public bool ShouldSerializeparking_brake()
        {
            return __pbn__parking_brake != null;
        }
        public void Resetparking_brake()
        {
            __pbn__parking_brake = null;
        }
        private bool? __pbn__parking_brake;

        [global::ProtoBuf.ProtoMember(9)]
        public double speed
        {
            get { return __pbn__speed.GetValueOrDefault(); }
            set { __pbn__speed = value; }
        }
        public bool ShouldSerializespeed()
        {
            return __pbn__speed != null;
        }
        public void Resetspeed()
        {
            __pbn__speed = null;
        }
        private double? __pbn__speed;

        [global::ProtoBuf.ProtoMember(10)]
        public double acceleration
        {
            get { return __pbn__acceleration.GetValueOrDefault(); }
            set { __pbn__acceleration = value; }
        }
        public bool ShouldSerializeacceleration()
        {
            return __pbn__acceleration != null;
        }
        public void Resetacceleration()
        {
            __pbn__acceleration = null;
        }
        private double? __pbn__acceleration;

        [global::ProtoBuf.ProtoMember(16)]
        [global::System.Obsolete]
        public bool reset_model
        {
            get { return __pbn__reset_model.GetValueOrDefault(); }
            set { __pbn__reset_model = value; }
        }
        public bool ShouldSerializereset_model()
        {
            return __pbn__reset_model != null;
        }
        public void Resetreset_model()
        {
            __pbn__reset_model = null;
        }
        private bool? __pbn__reset_model;

        [global::ProtoBuf.ProtoMember(17)]
        public bool engine_on_off
        {
            get { return __pbn__engine_on_off.GetValueOrDefault(); }
            set { __pbn__engine_on_off = value; }
        }
        public bool ShouldSerializeengine_on_off()
        {
            return __pbn__engine_on_off != null;
        }
        public void Resetengine_on_off()
        {
            __pbn__engine_on_off = null;
        }
        private bool? __pbn__engine_on_off;

        [global::ProtoBuf.ProtoMember(18)]
        public double trajectory_fraction
        {
            get { return __pbn__trajectory_fraction.GetValueOrDefault(); }
            set { __pbn__trajectory_fraction = value; }
        }
        public bool ShouldSerializetrajectory_fraction()
        {
            return __pbn__trajectory_fraction != null;
        }
        public void Resettrajectory_fraction()
        {
            __pbn__trajectory_fraction = null;
        }
        private double? __pbn__trajectory_fraction;

        [global::ProtoBuf.ProtoMember(19)]
        [global::System.ComponentModel.DefaultValue(global::apollo.canbus.Chassis.DrivingMode.CompleteManual)]
        [global::System.Obsolete]
        public global::apollo.canbus.Chassis.DrivingMode driving_mode
        {
            get { return __pbn__driving_mode ?? global::apollo.canbus.Chassis.DrivingMode.CompleteManual; }
            set { __pbn__driving_mode = value; }
        }
        public bool ShouldSerializedriving_mode()
        {
            return __pbn__driving_mode != null;
        }
        public void Resetdriving_mode()
        {
            __pbn__driving_mode = null;
        }
        private global::apollo.canbus.Chassis.DrivingMode? __pbn__driving_mode;

        [global::ProtoBuf.ProtoMember(20)]
        [global::System.ComponentModel.DefaultValue(global::apollo.canbus.Chassis.GearPosition.GearNeutral)]
        public global::apollo.canbus.Chassis.GearPosition gear_location
        {
            get { return __pbn__gear_location ?? global::apollo.canbus.Chassis.GearPosition.GearNeutral; }
            set { __pbn__gear_location = value; }
        }
        public bool ShouldSerializegear_location()
        {
            return __pbn__gear_location != null;
        }
        public void Resetgear_location()
        {
            __pbn__gear_location = null;
        }
        private global::apollo.canbus.Chassis.GearPosition? __pbn__gear_location;

        [global::ProtoBuf.ProtoMember(22)]
        public Debug debug { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public global::apollo.common.VehicleSignal signal { get; set; }

        [global::ProtoBuf.ProtoMember(24)]
        public LatencyStats latency_stats { get; set; }

        [global::ProtoBuf.ProtoMember(25)]
        public PadMessage pad_msg { get; set; }

        [global::ProtoBuf.ProtoMember(26)]
        public global::apollo.common.EngageAdvice engage_advice { get; set; }

        [global::ProtoBuf.ProtoMember(27)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool is_in_safe_mode
        {
            get { return __pbn__is_in_safe_mode ?? false; }
            set { __pbn__is_in_safe_mode = value; }
        }
        public bool ShouldSerializeis_in_safe_mode()
        {
            return __pbn__is_in_safe_mode != null;
        }
        public void Resetis_in_safe_mode()
        {
            __pbn__is_in_safe_mode = null;
        }
        private bool? __pbn__is_in_safe_mode;

        [global::ProtoBuf.ProtoMember(13)]
        [global::System.Obsolete]
        public bool left_turn
        {
            get { return __pbn__left_turn.GetValueOrDefault(); }
            set { __pbn__left_turn = value; }
        }
        public bool ShouldSerializeleft_turn()
        {
            return __pbn__left_turn != null;
        }
        public void Resetleft_turn()
        {
            __pbn__left_turn = null;
        }
        private bool? __pbn__left_turn;

        [global::ProtoBuf.ProtoMember(14)]
        [global::System.Obsolete]
        public bool right_turn
        {
            get { return __pbn__right_turn.GetValueOrDefault(); }
            set { __pbn__right_turn = value; }
        }
        public bool ShouldSerializeright_turn()
        {
            return __pbn__right_turn != null;
        }
        public void Resetright_turn()
        {
            __pbn__right_turn = null;
        }
        private bool? __pbn__right_turn;

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.Obsolete]
        public bool high_beam
        {
            get { return __pbn__high_beam.GetValueOrDefault(); }
            set { __pbn__high_beam = value; }
        }
        public bool ShouldSerializehigh_beam()
        {
            return __pbn__high_beam != null;
        }
        public void Resethigh_beam()
        {
            __pbn__high_beam = null;
        }
        private bool? __pbn__high_beam;

        [global::ProtoBuf.ProtoMember(12)]
        [global::System.Obsolete]
        public bool low_beam
        {
            get { return __pbn__low_beam.GetValueOrDefault(); }
            set { __pbn__low_beam = value; }
        }
        public bool ShouldSerializelow_beam()
        {
            return __pbn__low_beam != null;
        }
        public void Resetlow_beam()
        {
            __pbn__low_beam = null;
        }
        private bool? __pbn__low_beam;

        [global::ProtoBuf.ProtoMember(15)]
        [global::System.Obsolete]
        public bool horn
        {
            get { return __pbn__horn.GetValueOrDefault(); }
            set { __pbn__horn = value; }
        }
        public bool ShouldSerializehorn()
        {
            return __pbn__horn != null;
        }
        public void Resethorn()
        {
            __pbn__horn = null;
        }
        private bool? __pbn__horn;

        [global::ProtoBuf.ProtoMember(21)]
        [global::System.ComponentModel.DefaultValue(TurnSignal.TurnNone)]
        [global::System.Obsolete]
        public TurnSignal turnsignal
        {
            get { return __pbn__turnsignal ?? TurnSignal.TurnNone; }
            set { __pbn__turnsignal = value; }
        }
        public bool ShouldSerializeturnsignal()
        {
            return __pbn__turnsignal != null;
        }
        public void Resetturnsignal()
        {
            __pbn__turnsignal = null;
        }
        private TurnSignal? __pbn__turnsignal;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SimpleLongitudinalDebug : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SimpleLongitudinalDebug()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public double station_reference
        {
            get { return __pbn__station_reference.GetValueOrDefault(); }
            set { __pbn__station_reference = value; }
        }
        public bool ShouldSerializestation_reference()
        {
            return __pbn__station_reference != null;
        }
        public void Resetstation_reference()
        {
            __pbn__station_reference = null;
        }
        private double? __pbn__station_reference;

        [global::ProtoBuf.ProtoMember(2)]
        public double station_error
        {
            get { return __pbn__station_error.GetValueOrDefault(); }
            set { __pbn__station_error = value; }
        }
        public bool ShouldSerializestation_error()
        {
            return __pbn__station_error != null;
        }
        public void Resetstation_error()
        {
            __pbn__station_error = null;
        }
        private double? __pbn__station_error;

        [global::ProtoBuf.ProtoMember(3)]
        public double station_error_limited
        {
            get { return __pbn__station_error_limited.GetValueOrDefault(); }
            set { __pbn__station_error_limited = value; }
        }
        public bool ShouldSerializestation_error_limited()
        {
            return __pbn__station_error_limited != null;
        }
        public void Resetstation_error_limited()
        {
            __pbn__station_error_limited = null;
        }
        private double? __pbn__station_error_limited;

        [global::ProtoBuf.ProtoMember(4)]
        public double preview_station_error
        {
            get { return __pbn__preview_station_error.GetValueOrDefault(); }
            set { __pbn__preview_station_error = value; }
        }
        public bool ShouldSerializepreview_station_error()
        {
            return __pbn__preview_station_error != null;
        }
        public void Resetpreview_station_error()
        {
            __pbn__preview_station_error = null;
        }
        private double? __pbn__preview_station_error;

        [global::ProtoBuf.ProtoMember(5)]
        public double speed_reference
        {
            get { return __pbn__speed_reference.GetValueOrDefault(); }
            set { __pbn__speed_reference = value; }
        }
        public bool ShouldSerializespeed_reference()
        {
            return __pbn__speed_reference != null;
        }
        public void Resetspeed_reference()
        {
            __pbn__speed_reference = null;
        }
        private double? __pbn__speed_reference;

        [global::ProtoBuf.ProtoMember(6)]
        public double speed_error
        {
            get { return __pbn__speed_error.GetValueOrDefault(); }
            set { __pbn__speed_error = value; }
        }
        public bool ShouldSerializespeed_error()
        {
            return __pbn__speed_error != null;
        }
        public void Resetspeed_error()
        {
            __pbn__speed_error = null;
        }
        private double? __pbn__speed_error;

        [global::ProtoBuf.ProtoMember(7)]
        public double speed_controller_input_limited
        {
            get { return __pbn__speed_controller_input_limited.GetValueOrDefault(); }
            set { __pbn__speed_controller_input_limited = value; }
        }
        public bool ShouldSerializespeed_controller_input_limited()
        {
            return __pbn__speed_controller_input_limited != null;
        }
        public void Resetspeed_controller_input_limited()
        {
            __pbn__speed_controller_input_limited = null;
        }
        private double? __pbn__speed_controller_input_limited;

        [global::ProtoBuf.ProtoMember(8)]
        public double preview_speed_reference
        {
            get { return __pbn__preview_speed_reference.GetValueOrDefault(); }
            set { __pbn__preview_speed_reference = value; }
        }
        public bool ShouldSerializepreview_speed_reference()
        {
            return __pbn__preview_speed_reference != null;
        }
        public void Resetpreview_speed_reference()
        {
            __pbn__preview_speed_reference = null;
        }
        private double? __pbn__preview_speed_reference;

        [global::ProtoBuf.ProtoMember(9)]
        public double preview_speed_error
        {
            get { return __pbn__preview_speed_error.GetValueOrDefault(); }
            set { __pbn__preview_speed_error = value; }
        }
        public bool ShouldSerializepreview_speed_error()
        {
            return __pbn__preview_speed_error != null;
        }
        public void Resetpreview_speed_error()
        {
            __pbn__preview_speed_error = null;
        }
        private double? __pbn__preview_speed_error;

        [global::ProtoBuf.ProtoMember(10)]
        public double preview_acceleration_reference
        {
            get { return __pbn__preview_acceleration_reference.GetValueOrDefault(); }
            set { __pbn__preview_acceleration_reference = value; }
        }
        public bool ShouldSerializepreview_acceleration_reference()
        {
            return __pbn__preview_acceleration_reference != null;
        }
        public void Resetpreview_acceleration_reference()
        {
            __pbn__preview_acceleration_reference = null;
        }
        private double? __pbn__preview_acceleration_reference;

        [global::ProtoBuf.ProtoMember(11)]
        public double acceleration_cmd_closeloop
        {
            get { return __pbn__acceleration_cmd_closeloop.GetValueOrDefault(); }
            set { __pbn__acceleration_cmd_closeloop = value; }
        }
        public bool ShouldSerializeacceleration_cmd_closeloop()
        {
            return __pbn__acceleration_cmd_closeloop != null;
        }
        public void Resetacceleration_cmd_closeloop()
        {
            __pbn__acceleration_cmd_closeloop = null;
        }
        private double? __pbn__acceleration_cmd_closeloop;

        [global::ProtoBuf.ProtoMember(12)]
        public double acceleration_cmd
        {
            get { return __pbn__acceleration_cmd.GetValueOrDefault(); }
            set { __pbn__acceleration_cmd = value; }
        }
        public bool ShouldSerializeacceleration_cmd()
        {
            return __pbn__acceleration_cmd != null;
        }
        public void Resetacceleration_cmd()
        {
            __pbn__acceleration_cmd = null;
        }
        private double? __pbn__acceleration_cmd;

        [global::ProtoBuf.ProtoMember(13)]
        public double acceleration_lookup
        {
            get { return __pbn__acceleration_lookup.GetValueOrDefault(); }
            set { __pbn__acceleration_lookup = value; }
        }
        public bool ShouldSerializeacceleration_lookup()
        {
            return __pbn__acceleration_lookup != null;
        }
        public void Resetacceleration_lookup()
        {
            __pbn__acceleration_lookup = null;
        }
        private double? __pbn__acceleration_lookup;

        [global::ProtoBuf.ProtoMember(14)]
        public double speed_lookup
        {
            get { return __pbn__speed_lookup.GetValueOrDefault(); }
            set { __pbn__speed_lookup = value; }
        }
        public bool ShouldSerializespeed_lookup()
        {
            return __pbn__speed_lookup != null;
        }
        public void Resetspeed_lookup()
        {
            __pbn__speed_lookup = null;
        }
        private double? __pbn__speed_lookup;

        [global::ProtoBuf.ProtoMember(15)]
        public double calibration_value
        {
            get { return __pbn__calibration_value.GetValueOrDefault(); }
            set { __pbn__calibration_value = value; }
        }
        public bool ShouldSerializecalibration_value()
        {
            return __pbn__calibration_value != null;
        }
        public void Resetcalibration_value()
        {
            __pbn__calibration_value = null;
        }
        private double? __pbn__calibration_value;

        [global::ProtoBuf.ProtoMember(16)]
        public double throttle_cmd
        {
            get { return __pbn__throttle_cmd.GetValueOrDefault(); }
            set { __pbn__throttle_cmd = value; }
        }
        public bool ShouldSerializethrottle_cmd()
        {
            return __pbn__throttle_cmd != null;
        }
        public void Resetthrottle_cmd()
        {
            __pbn__throttle_cmd = null;
        }
        private double? __pbn__throttle_cmd;

        [global::ProtoBuf.ProtoMember(17)]
        public double brake_cmd
        {
            get { return __pbn__brake_cmd.GetValueOrDefault(); }
            set { __pbn__brake_cmd = value; }
        }
        public bool ShouldSerializebrake_cmd()
        {
            return __pbn__brake_cmd != null;
        }
        public void Resetbrake_cmd()
        {
            __pbn__brake_cmd = null;
        }
        private double? __pbn__brake_cmd;

        [global::ProtoBuf.ProtoMember(18)]
        public bool is_full_stop
        {
            get { return __pbn__is_full_stop.GetValueOrDefault(); }
            set { __pbn__is_full_stop = value; }
        }
        public bool ShouldSerializeis_full_stop()
        {
            return __pbn__is_full_stop != null;
        }
        public void Resetis_full_stop()
        {
            __pbn__is_full_stop = null;
        }
        private bool? __pbn__is_full_stop;

        [global::ProtoBuf.ProtoMember(19)]
        public double slope_offset_compensation
        {
            get { return __pbn__slope_offset_compensation.GetValueOrDefault(); }
            set { __pbn__slope_offset_compensation = value; }
        }
        public bool ShouldSerializeslope_offset_compensation()
        {
            return __pbn__slope_offset_compensation != null;
        }
        public void Resetslope_offset_compensation()
        {
            __pbn__slope_offset_compensation = null;
        }
        private double? __pbn__slope_offset_compensation;

        [global::ProtoBuf.ProtoMember(20)]
        public double current_station
        {
            get { return __pbn__current_station.GetValueOrDefault(); }
            set { __pbn__current_station = value; }
        }
        public bool ShouldSerializecurrent_station()
        {
            return __pbn__current_station != null;
        }
        public void Resetcurrent_station()
        {
            __pbn__current_station = null;
        }
        private double? __pbn__current_station;

        [global::ProtoBuf.ProtoMember(21)]
        public double path_remain
        {
            get { return __pbn__path_remain.GetValueOrDefault(); }
            set { __pbn__path_remain = value; }
        }
        public bool ShouldSerializepath_remain()
        {
            return __pbn__path_remain != null;
        }
        public void Resetpath_remain()
        {
            __pbn__path_remain = null;
        }
        private double? __pbn__path_remain;

        [global::ProtoBuf.ProtoMember(22)]
        public int pid_saturation_status
        {
            get { return __pbn__pid_saturation_status.GetValueOrDefault(); }
            set { __pbn__pid_saturation_status = value; }
        }
        public bool ShouldSerializepid_saturation_status()
        {
            return __pbn__pid_saturation_status != null;
        }
        public void Resetpid_saturation_status()
        {
            __pbn__pid_saturation_status = null;
        }
        private int? __pbn__pid_saturation_status;

        [global::ProtoBuf.ProtoMember(23)]
        public int leadlag_saturation_status
        {
            get { return __pbn__leadlag_saturation_status.GetValueOrDefault(); }
            set { __pbn__leadlag_saturation_status = value; }
        }
        public bool ShouldSerializeleadlag_saturation_status()
        {
            return __pbn__leadlag_saturation_status != null;
        }
        public void Resetleadlag_saturation_status()
        {
            __pbn__leadlag_saturation_status = null;
        }
        private int? __pbn__leadlag_saturation_status;

        [global::ProtoBuf.ProtoMember(24)]
        public double speed_offset
        {
            get { return __pbn__speed_offset.GetValueOrDefault(); }
            set { __pbn__speed_offset = value; }
        }
        public bool ShouldSerializespeed_offset()
        {
            return __pbn__speed_offset != null;
        }
        public void Resetspeed_offset()
        {
            __pbn__speed_offset = null;
        }
        private double? __pbn__speed_offset;

        [global::ProtoBuf.ProtoMember(25)]
        public double current_speed
        {
            get { return __pbn__current_speed.GetValueOrDefault(); }
            set { __pbn__current_speed = value; }
        }
        public bool ShouldSerializecurrent_speed()
        {
            return __pbn__current_speed != null;
        }
        public void Resetcurrent_speed()
        {
            __pbn__current_speed = null;
        }
        private double? __pbn__current_speed;

        [global::ProtoBuf.ProtoMember(26)]
        public double acceleration_reference
        {
            get { return __pbn__acceleration_reference.GetValueOrDefault(); }
            set { __pbn__acceleration_reference = value; }
        }
        public bool ShouldSerializeacceleration_reference()
        {
            return __pbn__acceleration_reference != null;
        }
        public void Resetacceleration_reference()
        {
            __pbn__acceleration_reference = null;
        }
        private double? __pbn__acceleration_reference;

        [global::ProtoBuf.ProtoMember(27)]
        public double current_acceleration
        {
            get { return __pbn__current_acceleration.GetValueOrDefault(); }
            set { __pbn__current_acceleration = value; }
        }
        public bool ShouldSerializecurrent_acceleration()
        {
            return __pbn__current_acceleration != null;
        }
        public void Resetcurrent_acceleration()
        {
            __pbn__current_acceleration = null;
        }
        private double? __pbn__current_acceleration;

        [global::ProtoBuf.ProtoMember(28)]
        public double acceleration_error
        {
            get { return __pbn__acceleration_error.GetValueOrDefault(); }
            set { __pbn__acceleration_error = value; }
        }
        public bool ShouldSerializeacceleration_error()
        {
            return __pbn__acceleration_error != null;
        }
        public void Resetacceleration_error()
        {
            __pbn__acceleration_error = null;
        }
        private double? __pbn__acceleration_error;

        [global::ProtoBuf.ProtoMember(29)]
        public double jerk_reference
        {
            get { return __pbn__jerk_reference.GetValueOrDefault(); }
            set { __pbn__jerk_reference = value; }
        }
        public bool ShouldSerializejerk_reference()
        {
            return __pbn__jerk_reference != null;
        }
        public void Resetjerk_reference()
        {
            __pbn__jerk_reference = null;
        }
        private double? __pbn__jerk_reference;

        [global::ProtoBuf.ProtoMember(30)]
        public double current_jerk
        {
            get { return __pbn__current_jerk.GetValueOrDefault(); }
            set { __pbn__current_jerk = value; }
        }
        public bool ShouldSerializecurrent_jerk()
        {
            return __pbn__current_jerk != null;
        }
        public void Resetcurrent_jerk()
        {
            __pbn__current_jerk = null;
        }
        private double? __pbn__current_jerk;

        [global::ProtoBuf.ProtoMember(31)]
        public double jerk_error
        {
            get { return __pbn__jerk_error.GetValueOrDefault(); }
            set { __pbn__jerk_error = value; }
        }
        public bool ShouldSerializejerk_error()
        {
            return __pbn__jerk_error != null;
        }
        public void Resetjerk_error()
        {
            __pbn__jerk_error = null;
        }
        private double? __pbn__jerk_error;

        [global::ProtoBuf.ProtoMember(32)]
        public global::apollo.common.TrajectoryPoint current_matched_point { get; set; }

        [global::ProtoBuf.ProtoMember(33)]
        public global::apollo.common.TrajectoryPoint current_reference_point { get; set; }

        [global::ProtoBuf.ProtoMember(34)]
        public global::apollo.common.TrajectoryPoint preview_reference_point { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SimpleLateralDebug : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SimpleLateralDebug()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public double lateral_error
        {
            get { return __pbn__lateral_error.GetValueOrDefault(); }
            set { __pbn__lateral_error = value; }
        }
        public bool ShouldSerializelateral_error()
        {
            return __pbn__lateral_error != null;
        }
        public void Resetlateral_error()
        {
            __pbn__lateral_error = null;
        }
        private double? __pbn__lateral_error;

        [global::ProtoBuf.ProtoMember(2)]
        public double ref_heading
        {
            get { return __pbn__ref_heading.GetValueOrDefault(); }
            set { __pbn__ref_heading = value; }
        }
        public bool ShouldSerializeref_heading()
        {
            return __pbn__ref_heading != null;
        }
        public void Resetref_heading()
        {
            __pbn__ref_heading = null;
        }
        private double? __pbn__ref_heading;

        [global::ProtoBuf.ProtoMember(3)]
        public double heading
        {
            get { return __pbn__heading.GetValueOrDefault(); }
            set { __pbn__heading = value; }
        }
        public bool ShouldSerializeheading()
        {
            return __pbn__heading != null;
        }
        public void Resetheading()
        {
            __pbn__heading = null;
        }
        private double? __pbn__heading;

        [global::ProtoBuf.ProtoMember(4)]
        public double heading_error
        {
            get { return __pbn__heading_error.GetValueOrDefault(); }
            set { __pbn__heading_error = value; }
        }
        public bool ShouldSerializeheading_error()
        {
            return __pbn__heading_error != null;
        }
        public void Resetheading_error()
        {
            __pbn__heading_error = null;
        }
        private double? __pbn__heading_error;

        [global::ProtoBuf.ProtoMember(5)]
        public double heading_error_rate
        {
            get { return __pbn__heading_error_rate.GetValueOrDefault(); }
            set { __pbn__heading_error_rate = value; }
        }
        public bool ShouldSerializeheading_error_rate()
        {
            return __pbn__heading_error_rate != null;
        }
        public void Resetheading_error_rate()
        {
            __pbn__heading_error_rate = null;
        }
        private double? __pbn__heading_error_rate;

        [global::ProtoBuf.ProtoMember(6)]
        public double lateral_error_rate
        {
            get { return __pbn__lateral_error_rate.GetValueOrDefault(); }
            set { __pbn__lateral_error_rate = value; }
        }
        public bool ShouldSerializelateral_error_rate()
        {
            return __pbn__lateral_error_rate != null;
        }
        public void Resetlateral_error_rate()
        {
            __pbn__lateral_error_rate = null;
        }
        private double? __pbn__lateral_error_rate;

        [global::ProtoBuf.ProtoMember(7)]
        public double curvature
        {
            get { return __pbn__curvature.GetValueOrDefault(); }
            set { __pbn__curvature = value; }
        }
        public bool ShouldSerializecurvature()
        {
            return __pbn__curvature != null;
        }
        public void Resetcurvature()
        {
            __pbn__curvature = null;
        }
        private double? __pbn__curvature;

        [global::ProtoBuf.ProtoMember(8)]
        public double steer_angle
        {
            get { return __pbn__steer_angle.GetValueOrDefault(); }
            set { __pbn__steer_angle = value; }
        }
        public bool ShouldSerializesteer_angle()
        {
            return __pbn__steer_angle != null;
        }
        public void Resetsteer_angle()
        {
            __pbn__steer_angle = null;
        }
        private double? __pbn__steer_angle;

        [global::ProtoBuf.ProtoMember(9)]
        public double steer_angle_feedforward
        {
            get { return __pbn__steer_angle_feedforward.GetValueOrDefault(); }
            set { __pbn__steer_angle_feedforward = value; }
        }
        public bool ShouldSerializesteer_angle_feedforward()
        {
            return __pbn__steer_angle_feedforward != null;
        }
        public void Resetsteer_angle_feedforward()
        {
            __pbn__steer_angle_feedforward = null;
        }
        private double? __pbn__steer_angle_feedforward;

        [global::ProtoBuf.ProtoMember(10)]
        public double steer_angle_lateral_contribution
        {
            get { return __pbn__steer_angle_lateral_contribution.GetValueOrDefault(); }
            set { __pbn__steer_angle_lateral_contribution = value; }
        }
        public bool ShouldSerializesteer_angle_lateral_contribution()
        {
            return __pbn__steer_angle_lateral_contribution != null;
        }
        public void Resetsteer_angle_lateral_contribution()
        {
            __pbn__steer_angle_lateral_contribution = null;
        }
        private double? __pbn__steer_angle_lateral_contribution;

        [global::ProtoBuf.ProtoMember(11)]
        public double steer_angle_lateral_rate_contribution
        {
            get { return __pbn__steer_angle_lateral_rate_contribution.GetValueOrDefault(); }
            set { __pbn__steer_angle_lateral_rate_contribution = value; }
        }
        public bool ShouldSerializesteer_angle_lateral_rate_contribution()
        {
            return __pbn__steer_angle_lateral_rate_contribution != null;
        }
        public void Resetsteer_angle_lateral_rate_contribution()
        {
            __pbn__steer_angle_lateral_rate_contribution = null;
        }
        private double? __pbn__steer_angle_lateral_rate_contribution;

        [global::ProtoBuf.ProtoMember(12)]
        public double steer_angle_heading_contribution
        {
            get { return __pbn__steer_angle_heading_contribution.GetValueOrDefault(); }
            set { __pbn__steer_angle_heading_contribution = value; }
        }
        public bool ShouldSerializesteer_angle_heading_contribution()
        {
            return __pbn__steer_angle_heading_contribution != null;
        }
        public void Resetsteer_angle_heading_contribution()
        {
            __pbn__steer_angle_heading_contribution = null;
        }
        private double? __pbn__steer_angle_heading_contribution;

        [global::ProtoBuf.ProtoMember(13)]
        public double steer_angle_heading_rate_contribution
        {
            get { return __pbn__steer_angle_heading_rate_contribution.GetValueOrDefault(); }
            set { __pbn__steer_angle_heading_rate_contribution = value; }
        }
        public bool ShouldSerializesteer_angle_heading_rate_contribution()
        {
            return __pbn__steer_angle_heading_rate_contribution != null;
        }
        public void Resetsteer_angle_heading_rate_contribution()
        {
            __pbn__steer_angle_heading_rate_contribution = null;
        }
        private double? __pbn__steer_angle_heading_rate_contribution;

        [global::ProtoBuf.ProtoMember(14)]
        public double steer_angle_feedback
        {
            get { return __pbn__steer_angle_feedback.GetValueOrDefault(); }
            set { __pbn__steer_angle_feedback = value; }
        }
        public bool ShouldSerializesteer_angle_feedback()
        {
            return __pbn__steer_angle_feedback != null;
        }
        public void Resetsteer_angle_feedback()
        {
            __pbn__steer_angle_feedback = null;
        }
        private double? __pbn__steer_angle_feedback;

        [global::ProtoBuf.ProtoMember(15)]
        public double steering_position
        {
            get { return __pbn__steering_position.GetValueOrDefault(); }
            set { __pbn__steering_position = value; }
        }
        public bool ShouldSerializesteering_position()
        {
            return __pbn__steering_position != null;
        }
        public void Resetsteering_position()
        {
            __pbn__steering_position = null;
        }
        private double? __pbn__steering_position;

        [global::ProtoBuf.ProtoMember(16)]
        public double ref_speed
        {
            get { return __pbn__ref_speed.GetValueOrDefault(); }
            set { __pbn__ref_speed = value; }
        }
        public bool ShouldSerializeref_speed()
        {
            return __pbn__ref_speed != null;
        }
        public void Resetref_speed()
        {
            __pbn__ref_speed = null;
        }
        private double? __pbn__ref_speed;

        [global::ProtoBuf.ProtoMember(17)]
        public double steer_angle_limited
        {
            get { return __pbn__steer_angle_limited.GetValueOrDefault(); }
            set { __pbn__steer_angle_limited = value; }
        }
        public bool ShouldSerializesteer_angle_limited()
        {
            return __pbn__steer_angle_limited != null;
        }
        public void Resetsteer_angle_limited()
        {
            __pbn__steer_angle_limited = null;
        }
        private double? __pbn__steer_angle_limited;

        [global::ProtoBuf.ProtoMember(18)]
        public double lateral_acceleration
        {
            get { return __pbn__lateral_acceleration.GetValueOrDefault(); }
            set { __pbn__lateral_acceleration = value; }
        }
        public bool ShouldSerializelateral_acceleration()
        {
            return __pbn__lateral_acceleration != null;
        }
        public void Resetlateral_acceleration()
        {
            __pbn__lateral_acceleration = null;
        }
        private double? __pbn__lateral_acceleration;

        [global::ProtoBuf.ProtoMember(19)]
        public double lateral_jerk
        {
            get { return __pbn__lateral_jerk.GetValueOrDefault(); }
            set { __pbn__lateral_jerk = value; }
        }
        public bool ShouldSerializelateral_jerk()
        {
            return __pbn__lateral_jerk != null;
        }
        public void Resetlateral_jerk()
        {
            __pbn__lateral_jerk = null;
        }
        private double? __pbn__lateral_jerk;

        [global::ProtoBuf.ProtoMember(20)]
        public double ref_heading_rate
        {
            get { return __pbn__ref_heading_rate.GetValueOrDefault(); }
            set { __pbn__ref_heading_rate = value; }
        }
        public bool ShouldSerializeref_heading_rate()
        {
            return __pbn__ref_heading_rate != null;
        }
        public void Resetref_heading_rate()
        {
            __pbn__ref_heading_rate = null;
        }
        private double? __pbn__ref_heading_rate;

        [global::ProtoBuf.ProtoMember(21)]
        public double heading_rate
        {
            get { return __pbn__heading_rate.GetValueOrDefault(); }
            set { __pbn__heading_rate = value; }
        }
        public bool ShouldSerializeheading_rate()
        {
            return __pbn__heading_rate != null;
        }
        public void Resetheading_rate()
        {
            __pbn__heading_rate = null;
        }
        private double? __pbn__heading_rate;

        [global::ProtoBuf.ProtoMember(22)]
        public double ref_heading_acceleration
        {
            get { return __pbn__ref_heading_acceleration.GetValueOrDefault(); }
            set { __pbn__ref_heading_acceleration = value; }
        }
        public bool ShouldSerializeref_heading_acceleration()
        {
            return __pbn__ref_heading_acceleration != null;
        }
        public void Resetref_heading_acceleration()
        {
            __pbn__ref_heading_acceleration = null;
        }
        private double? __pbn__ref_heading_acceleration;

        [global::ProtoBuf.ProtoMember(23)]
        public double heading_acceleration
        {
            get { return __pbn__heading_acceleration.GetValueOrDefault(); }
            set { __pbn__heading_acceleration = value; }
        }
        public bool ShouldSerializeheading_acceleration()
        {
            return __pbn__heading_acceleration != null;
        }
        public void Resetheading_acceleration()
        {
            __pbn__heading_acceleration = null;
        }
        private double? __pbn__heading_acceleration;

        [global::ProtoBuf.ProtoMember(24)]
        public double heading_error_acceleration
        {
            get { return __pbn__heading_error_acceleration.GetValueOrDefault(); }
            set { __pbn__heading_error_acceleration = value; }
        }
        public bool ShouldSerializeheading_error_acceleration()
        {
            return __pbn__heading_error_acceleration != null;
        }
        public void Resetheading_error_acceleration()
        {
            __pbn__heading_error_acceleration = null;
        }
        private double? __pbn__heading_error_acceleration;

        [global::ProtoBuf.ProtoMember(25)]
        public double ref_heading_jerk
        {
            get { return __pbn__ref_heading_jerk.GetValueOrDefault(); }
            set { __pbn__ref_heading_jerk = value; }
        }
        public bool ShouldSerializeref_heading_jerk()
        {
            return __pbn__ref_heading_jerk != null;
        }
        public void Resetref_heading_jerk()
        {
            __pbn__ref_heading_jerk = null;
        }
        private double? __pbn__ref_heading_jerk;

        [global::ProtoBuf.ProtoMember(26)]
        public double heading_jerk
        {
            get { return __pbn__heading_jerk.GetValueOrDefault(); }
            set { __pbn__heading_jerk = value; }
        }
        public bool ShouldSerializeheading_jerk()
        {
            return __pbn__heading_jerk != null;
        }
        public void Resetheading_jerk()
        {
            __pbn__heading_jerk = null;
        }
        private double? __pbn__heading_jerk;

        [global::ProtoBuf.ProtoMember(27)]
        public double heading_error_jerk
        {
            get { return __pbn__heading_error_jerk.GetValueOrDefault(); }
            set { __pbn__heading_error_jerk = value; }
        }
        public bool ShouldSerializeheading_error_jerk()
        {
            return __pbn__heading_error_jerk != null;
        }
        public void Resetheading_error_jerk()
        {
            __pbn__heading_error_jerk = null;
        }
        private double? __pbn__heading_error_jerk;

        [global::ProtoBuf.ProtoMember(28)]
        public double lateral_error_feedback
        {
            get { return __pbn__lateral_error_feedback.GetValueOrDefault(); }
            set { __pbn__lateral_error_feedback = value; }
        }
        public bool ShouldSerializelateral_error_feedback()
        {
            return __pbn__lateral_error_feedback != null;
        }
        public void Resetlateral_error_feedback()
        {
            __pbn__lateral_error_feedback = null;
        }
        private double? __pbn__lateral_error_feedback;

        [global::ProtoBuf.ProtoMember(29)]
        public double heading_error_feedback
        {
            get { return __pbn__heading_error_feedback.GetValueOrDefault(); }
            set { __pbn__heading_error_feedback = value; }
        }
        public bool ShouldSerializeheading_error_feedback()
        {
            return __pbn__heading_error_feedback != null;
        }
        public void Resetheading_error_feedback()
        {
            __pbn__heading_error_feedback = null;
        }
        private double? __pbn__heading_error_feedback;

        [global::ProtoBuf.ProtoMember(30)]
        public global::apollo.common.TrajectoryPoint current_target_point { get; set; }

        [global::ProtoBuf.ProtoMember(31)]
        public double steer_angle_feedback_augment
        {
            get { return __pbn__steer_angle_feedback_augment.GetValueOrDefault(); }
            set { __pbn__steer_angle_feedback_augment = value; }
        }
        public bool ShouldSerializesteer_angle_feedback_augment()
        {
            return __pbn__steer_angle_feedback_augment != null;
        }
        public void Resetsteer_angle_feedback_augment()
        {
            __pbn__steer_angle_feedback_augment = null;
        }
        private double? __pbn__steer_angle_feedback_augment;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SimpleMPCDebug : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SimpleMPCDebug()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public double lateral_error
        {
            get { return __pbn__lateral_error.GetValueOrDefault(); }
            set { __pbn__lateral_error = value; }
        }
        public bool ShouldSerializelateral_error()
        {
            return __pbn__lateral_error != null;
        }
        public void Resetlateral_error()
        {
            __pbn__lateral_error = null;
        }
        private double? __pbn__lateral_error;

        [global::ProtoBuf.ProtoMember(2)]
        public double ref_heading
        {
            get { return __pbn__ref_heading.GetValueOrDefault(); }
            set { __pbn__ref_heading = value; }
        }
        public bool ShouldSerializeref_heading()
        {
            return __pbn__ref_heading != null;
        }
        public void Resetref_heading()
        {
            __pbn__ref_heading = null;
        }
        private double? __pbn__ref_heading;

        [global::ProtoBuf.ProtoMember(3)]
        public double heading
        {
            get { return __pbn__heading.GetValueOrDefault(); }
            set { __pbn__heading = value; }
        }
        public bool ShouldSerializeheading()
        {
            return __pbn__heading != null;
        }
        public void Resetheading()
        {
            __pbn__heading = null;
        }
        private double? __pbn__heading;

        [global::ProtoBuf.ProtoMember(4)]
        public double heading_error
        {
            get { return __pbn__heading_error.GetValueOrDefault(); }
            set { __pbn__heading_error = value; }
        }
        public bool ShouldSerializeheading_error()
        {
            return __pbn__heading_error != null;
        }
        public void Resetheading_error()
        {
            __pbn__heading_error = null;
        }
        private double? __pbn__heading_error;

        [global::ProtoBuf.ProtoMember(5)]
        public double heading_error_rate
        {
            get { return __pbn__heading_error_rate.GetValueOrDefault(); }
            set { __pbn__heading_error_rate = value; }
        }
        public bool ShouldSerializeheading_error_rate()
        {
            return __pbn__heading_error_rate != null;
        }
        public void Resetheading_error_rate()
        {
            __pbn__heading_error_rate = null;
        }
        private double? __pbn__heading_error_rate;

        [global::ProtoBuf.ProtoMember(6)]
        public double lateral_error_rate
        {
            get { return __pbn__lateral_error_rate.GetValueOrDefault(); }
            set { __pbn__lateral_error_rate = value; }
        }
        public bool ShouldSerializelateral_error_rate()
        {
            return __pbn__lateral_error_rate != null;
        }
        public void Resetlateral_error_rate()
        {
            __pbn__lateral_error_rate = null;
        }
        private double? __pbn__lateral_error_rate;

        [global::ProtoBuf.ProtoMember(7)]
        public double curvature
        {
            get { return __pbn__curvature.GetValueOrDefault(); }
            set { __pbn__curvature = value; }
        }
        public bool ShouldSerializecurvature()
        {
            return __pbn__curvature != null;
        }
        public void Resetcurvature()
        {
            __pbn__curvature = null;
        }
        private double? __pbn__curvature;

        [global::ProtoBuf.ProtoMember(8)]
        public double steer_angle
        {
            get { return __pbn__steer_angle.GetValueOrDefault(); }
            set { __pbn__steer_angle = value; }
        }
        public bool ShouldSerializesteer_angle()
        {
            return __pbn__steer_angle != null;
        }
        public void Resetsteer_angle()
        {
            __pbn__steer_angle = null;
        }
        private double? __pbn__steer_angle;

        [global::ProtoBuf.ProtoMember(9)]
        public double steer_angle_feedforward
        {
            get { return __pbn__steer_angle_feedforward.GetValueOrDefault(); }
            set { __pbn__steer_angle_feedforward = value; }
        }
        public bool ShouldSerializesteer_angle_feedforward()
        {
            return __pbn__steer_angle_feedforward != null;
        }
        public void Resetsteer_angle_feedforward()
        {
            __pbn__steer_angle_feedforward = null;
        }
        private double? __pbn__steer_angle_feedforward;

        [global::ProtoBuf.ProtoMember(10)]
        public double steer_angle_lateral_contribution
        {
            get { return __pbn__steer_angle_lateral_contribution.GetValueOrDefault(); }
            set { __pbn__steer_angle_lateral_contribution = value; }
        }
        public bool ShouldSerializesteer_angle_lateral_contribution()
        {
            return __pbn__steer_angle_lateral_contribution != null;
        }
        public void Resetsteer_angle_lateral_contribution()
        {
            __pbn__steer_angle_lateral_contribution = null;
        }
        private double? __pbn__steer_angle_lateral_contribution;

        [global::ProtoBuf.ProtoMember(11)]
        public double steer_angle_lateral_rate_contribution
        {
            get { return __pbn__steer_angle_lateral_rate_contribution.GetValueOrDefault(); }
            set { __pbn__steer_angle_lateral_rate_contribution = value; }
        }
        public bool ShouldSerializesteer_angle_lateral_rate_contribution()
        {
            return __pbn__steer_angle_lateral_rate_contribution != null;
        }
        public void Resetsteer_angle_lateral_rate_contribution()
        {
            __pbn__steer_angle_lateral_rate_contribution = null;
        }
        private double? __pbn__steer_angle_lateral_rate_contribution;

        [global::ProtoBuf.ProtoMember(12)]
        public double steer_angle_heading_contribution
        {
            get { return __pbn__steer_angle_heading_contribution.GetValueOrDefault(); }
            set { __pbn__steer_angle_heading_contribution = value; }
        }
        public bool ShouldSerializesteer_angle_heading_contribution()
        {
            return __pbn__steer_angle_heading_contribution != null;
        }
        public void Resetsteer_angle_heading_contribution()
        {
            __pbn__steer_angle_heading_contribution = null;
        }
        private double? __pbn__steer_angle_heading_contribution;

        [global::ProtoBuf.ProtoMember(13)]
        public double steer_angle_heading_rate_contribution
        {
            get { return __pbn__steer_angle_heading_rate_contribution.GetValueOrDefault(); }
            set { __pbn__steer_angle_heading_rate_contribution = value; }
        }
        public bool ShouldSerializesteer_angle_heading_rate_contribution()
        {
            return __pbn__steer_angle_heading_rate_contribution != null;
        }
        public void Resetsteer_angle_heading_rate_contribution()
        {
            __pbn__steer_angle_heading_rate_contribution = null;
        }
        private double? __pbn__steer_angle_heading_rate_contribution;

        [global::ProtoBuf.ProtoMember(14)]
        public double steer_angle_feedback
        {
            get { return __pbn__steer_angle_feedback.GetValueOrDefault(); }
            set { __pbn__steer_angle_feedback = value; }
        }
        public bool ShouldSerializesteer_angle_feedback()
        {
            return __pbn__steer_angle_feedback != null;
        }
        public void Resetsteer_angle_feedback()
        {
            __pbn__steer_angle_feedback = null;
        }
        private double? __pbn__steer_angle_feedback;

        [global::ProtoBuf.ProtoMember(15)]
        public double steering_position
        {
            get { return __pbn__steering_position.GetValueOrDefault(); }
            set { __pbn__steering_position = value; }
        }
        public bool ShouldSerializesteering_position()
        {
            return __pbn__steering_position != null;
        }
        public void Resetsteering_position()
        {
            __pbn__steering_position = null;
        }
        private double? __pbn__steering_position;

        [global::ProtoBuf.ProtoMember(16)]
        public double ref_speed
        {
            get { return __pbn__ref_speed.GetValueOrDefault(); }
            set { __pbn__ref_speed = value; }
        }
        public bool ShouldSerializeref_speed()
        {
            return __pbn__ref_speed != null;
        }
        public void Resetref_speed()
        {
            __pbn__ref_speed = null;
        }
        private double? __pbn__ref_speed;

        [global::ProtoBuf.ProtoMember(17)]
        public double steer_angle_limited
        {
            get { return __pbn__steer_angle_limited.GetValueOrDefault(); }
            set { __pbn__steer_angle_limited = value; }
        }
        public bool ShouldSerializesteer_angle_limited()
        {
            return __pbn__steer_angle_limited != null;
        }
        public void Resetsteer_angle_limited()
        {
            __pbn__steer_angle_limited = null;
        }
        private double? __pbn__steer_angle_limited;

        [global::ProtoBuf.ProtoMember(18)]
        public double station_reference
        {
            get { return __pbn__station_reference.GetValueOrDefault(); }
            set { __pbn__station_reference = value; }
        }
        public bool ShouldSerializestation_reference()
        {
            return __pbn__station_reference != null;
        }
        public void Resetstation_reference()
        {
            __pbn__station_reference = null;
        }
        private double? __pbn__station_reference;

        [global::ProtoBuf.ProtoMember(19)]
        public double station_error
        {
            get { return __pbn__station_error.GetValueOrDefault(); }
            set { __pbn__station_error = value; }
        }
        public bool ShouldSerializestation_error()
        {
            return __pbn__station_error != null;
        }
        public void Resetstation_error()
        {
            __pbn__station_error = null;
        }
        private double? __pbn__station_error;

        [global::ProtoBuf.ProtoMember(20)]
        public double speed_reference
        {
            get { return __pbn__speed_reference.GetValueOrDefault(); }
            set { __pbn__speed_reference = value; }
        }
        public bool ShouldSerializespeed_reference()
        {
            return __pbn__speed_reference != null;
        }
        public void Resetspeed_reference()
        {
            __pbn__speed_reference = null;
        }
        private double? __pbn__speed_reference;

        [global::ProtoBuf.ProtoMember(21)]
        public double speed_error
        {
            get { return __pbn__speed_error.GetValueOrDefault(); }
            set { __pbn__speed_error = value; }
        }
        public bool ShouldSerializespeed_error()
        {
            return __pbn__speed_error != null;
        }
        public void Resetspeed_error()
        {
            __pbn__speed_error = null;
        }
        private double? __pbn__speed_error;

        [global::ProtoBuf.ProtoMember(22)]
        public double acceleration_reference
        {
            get { return __pbn__acceleration_reference.GetValueOrDefault(); }
            set { __pbn__acceleration_reference = value; }
        }
        public bool ShouldSerializeacceleration_reference()
        {
            return __pbn__acceleration_reference != null;
        }
        public void Resetacceleration_reference()
        {
            __pbn__acceleration_reference = null;
        }
        private double? __pbn__acceleration_reference;

        [global::ProtoBuf.ProtoMember(23)]
        public bool is_full_stop
        {
            get { return __pbn__is_full_stop.GetValueOrDefault(); }
            set { __pbn__is_full_stop = value; }
        }
        public bool ShouldSerializeis_full_stop()
        {
            return __pbn__is_full_stop != null;
        }
        public void Resetis_full_stop()
        {
            __pbn__is_full_stop = null;
        }
        private bool? __pbn__is_full_stop;

        [global::ProtoBuf.ProtoMember(24)]
        public double station_feedback
        {
            get { return __pbn__station_feedback.GetValueOrDefault(); }
            set { __pbn__station_feedback = value; }
        }
        public bool ShouldSerializestation_feedback()
        {
            return __pbn__station_feedback != null;
        }
        public void Resetstation_feedback()
        {
            __pbn__station_feedback = null;
        }
        private double? __pbn__station_feedback;

        [global::ProtoBuf.ProtoMember(25)]
        public double speed_feedback
        {
            get { return __pbn__speed_feedback.GetValueOrDefault(); }
            set { __pbn__speed_feedback = value; }
        }
        public bool ShouldSerializespeed_feedback()
        {
            return __pbn__speed_feedback != null;
        }
        public void Resetspeed_feedback()
        {
            __pbn__speed_feedback = null;
        }
        private double? __pbn__speed_feedback;

        [global::ProtoBuf.ProtoMember(26)]
        public double acceleration_cmd_closeloop
        {
            get { return __pbn__acceleration_cmd_closeloop.GetValueOrDefault(); }
            set { __pbn__acceleration_cmd_closeloop = value; }
        }
        public bool ShouldSerializeacceleration_cmd_closeloop()
        {
            return __pbn__acceleration_cmd_closeloop != null;
        }
        public void Resetacceleration_cmd_closeloop()
        {
            __pbn__acceleration_cmd_closeloop = null;
        }
        private double? __pbn__acceleration_cmd_closeloop;

        [global::ProtoBuf.ProtoMember(27)]
        public double acceleration_cmd
        {
            get { return __pbn__acceleration_cmd.GetValueOrDefault(); }
            set { __pbn__acceleration_cmd = value; }
        }
        public bool ShouldSerializeacceleration_cmd()
        {
            return __pbn__acceleration_cmd != null;
        }
        public void Resetacceleration_cmd()
        {
            __pbn__acceleration_cmd = null;
        }
        private double? __pbn__acceleration_cmd;

        [global::ProtoBuf.ProtoMember(28)]
        public double acceleration_lookup
        {
            get { return __pbn__acceleration_lookup.GetValueOrDefault(); }
            set { __pbn__acceleration_lookup = value; }
        }
        public bool ShouldSerializeacceleration_lookup()
        {
            return __pbn__acceleration_lookup != null;
        }
        public void Resetacceleration_lookup()
        {
            __pbn__acceleration_lookup = null;
        }
        private double? __pbn__acceleration_lookup;

        [global::ProtoBuf.ProtoMember(29)]
        public double speed_lookup
        {
            get { return __pbn__speed_lookup.GetValueOrDefault(); }
            set { __pbn__speed_lookup = value; }
        }
        public bool ShouldSerializespeed_lookup()
        {
            return __pbn__speed_lookup != null;
        }
        public void Resetspeed_lookup()
        {
            __pbn__speed_lookup = null;
        }
        private double? __pbn__speed_lookup;

        [global::ProtoBuf.ProtoMember(30)]
        public double calibration_value
        {
            get { return __pbn__calibration_value.GetValueOrDefault(); }
            set { __pbn__calibration_value = value; }
        }
        public bool ShouldSerializecalibration_value()
        {
            return __pbn__calibration_value != null;
        }
        public void Resetcalibration_value()
        {
            __pbn__calibration_value = null;
        }
        private double? __pbn__calibration_value;

        [global::ProtoBuf.ProtoMember(31)]
        public double steer_unconstraint_control_diff
        {
            get { return __pbn__steer_unconstraint_control_diff.GetValueOrDefault(); }
            set { __pbn__steer_unconstraint_control_diff = value; }
        }
        public bool ShouldSerializesteer_unconstraint_control_diff()
        {
            return __pbn__steer_unconstraint_control_diff != null;
        }
        public void Resetsteer_unconstraint_control_diff()
        {
            __pbn__steer_unconstraint_control_diff = null;
        }
        private double? __pbn__steer_unconstraint_control_diff;

        [global::ProtoBuf.ProtoMember(32)]
        public double steer_angle_feedforward_compensation
        {
            get { return __pbn__steer_angle_feedforward_compensation.GetValueOrDefault(); }
            set { __pbn__steer_angle_feedforward_compensation = value; }
        }
        public bool ShouldSerializesteer_angle_feedforward_compensation()
        {
            return __pbn__steer_angle_feedforward_compensation != null;
        }
        public void Resetsteer_angle_feedforward_compensation()
        {
            __pbn__steer_angle_feedforward_compensation = null;
        }
        private double? __pbn__steer_angle_feedforward_compensation;

        [global::ProtoBuf.ProtoMember(33)]
        public double[] matrix_q_updated { get; set; }

        [global::ProtoBuf.ProtoMember(34)]
        public double[] matrix_r_updated { get; set; }

        [global::ProtoBuf.ProtoMember(35)]
        public double lateral_acceleration
        {
            get { return __pbn__lateral_acceleration.GetValueOrDefault(); }
            set { __pbn__lateral_acceleration = value; }
        }
        public bool ShouldSerializelateral_acceleration()
        {
            return __pbn__lateral_acceleration != null;
        }
        public void Resetlateral_acceleration()
        {
            __pbn__lateral_acceleration = null;
        }
        private double? __pbn__lateral_acceleration;

        [global::ProtoBuf.ProtoMember(36)]
        public double lateral_jerk
        {
            get { return __pbn__lateral_jerk.GetValueOrDefault(); }
            set { __pbn__lateral_jerk = value; }
        }
        public bool ShouldSerializelateral_jerk()
        {
            return __pbn__lateral_jerk != null;
        }
        public void Resetlateral_jerk()
        {
            __pbn__lateral_jerk = null;
        }
        private double? __pbn__lateral_jerk;

        [global::ProtoBuf.ProtoMember(37)]
        public double ref_heading_rate
        {
            get { return __pbn__ref_heading_rate.GetValueOrDefault(); }
            set { __pbn__ref_heading_rate = value; }
        }
        public bool ShouldSerializeref_heading_rate()
        {
            return __pbn__ref_heading_rate != null;
        }
        public void Resetref_heading_rate()
        {
            __pbn__ref_heading_rate = null;
        }
        private double? __pbn__ref_heading_rate;

        [global::ProtoBuf.ProtoMember(38)]
        public double heading_rate
        {
            get { return __pbn__heading_rate.GetValueOrDefault(); }
            set { __pbn__heading_rate = value; }
        }
        public bool ShouldSerializeheading_rate()
        {
            return __pbn__heading_rate != null;
        }
        public void Resetheading_rate()
        {
            __pbn__heading_rate = null;
        }
        private double? __pbn__heading_rate;

        [global::ProtoBuf.ProtoMember(39)]
        public double ref_heading_acceleration
        {
            get { return __pbn__ref_heading_acceleration.GetValueOrDefault(); }
            set { __pbn__ref_heading_acceleration = value; }
        }
        public bool ShouldSerializeref_heading_acceleration()
        {
            return __pbn__ref_heading_acceleration != null;
        }
        public void Resetref_heading_acceleration()
        {
            __pbn__ref_heading_acceleration = null;
        }
        private double? __pbn__ref_heading_acceleration;

        [global::ProtoBuf.ProtoMember(40)]
        public double heading_acceleration
        {
            get { return __pbn__heading_acceleration.GetValueOrDefault(); }
            set { __pbn__heading_acceleration = value; }
        }
        public bool ShouldSerializeheading_acceleration()
        {
            return __pbn__heading_acceleration != null;
        }
        public void Resetheading_acceleration()
        {
            __pbn__heading_acceleration = null;
        }
        private double? __pbn__heading_acceleration;

        [global::ProtoBuf.ProtoMember(41)]
        public double heading_error_acceleration
        {
            get { return __pbn__heading_error_acceleration.GetValueOrDefault(); }
            set { __pbn__heading_error_acceleration = value; }
        }
        public bool ShouldSerializeheading_error_acceleration()
        {
            return __pbn__heading_error_acceleration != null;
        }
        public void Resetheading_error_acceleration()
        {
            __pbn__heading_error_acceleration = null;
        }
        private double? __pbn__heading_error_acceleration;

        [global::ProtoBuf.ProtoMember(42)]
        public double ref_heading_jerk
        {
            get { return __pbn__ref_heading_jerk.GetValueOrDefault(); }
            set { __pbn__ref_heading_jerk = value; }
        }
        public bool ShouldSerializeref_heading_jerk()
        {
            return __pbn__ref_heading_jerk != null;
        }
        public void Resetref_heading_jerk()
        {
            __pbn__ref_heading_jerk = null;
        }
        private double? __pbn__ref_heading_jerk;

        [global::ProtoBuf.ProtoMember(43)]
        public double heading_jerk
        {
            get { return __pbn__heading_jerk.GetValueOrDefault(); }
            set { __pbn__heading_jerk = value; }
        }
        public bool ShouldSerializeheading_jerk()
        {
            return __pbn__heading_jerk != null;
        }
        public void Resetheading_jerk()
        {
            __pbn__heading_jerk = null;
        }
        private double? __pbn__heading_jerk;

        [global::ProtoBuf.ProtoMember(44)]
        public double heading_error_jerk
        {
            get { return __pbn__heading_error_jerk.GetValueOrDefault(); }
            set { __pbn__heading_error_jerk = value; }
        }
        public bool ShouldSerializeheading_error_jerk()
        {
            return __pbn__heading_error_jerk != null;
        }
        public void Resetheading_error_jerk()
        {
            __pbn__heading_error_jerk = null;
        }
        private double? __pbn__heading_error_jerk;

        [global::ProtoBuf.ProtoMember(45)]
        public double acceleration_feedback
        {
            get { return __pbn__acceleration_feedback.GetValueOrDefault(); }
            set { __pbn__acceleration_feedback = value; }
        }
        public bool ShouldSerializeacceleration_feedback()
        {
            return __pbn__acceleration_feedback != null;
        }
        public void Resetacceleration_feedback()
        {
            __pbn__acceleration_feedback = null;
        }
        private double? __pbn__acceleration_feedback;

        [global::ProtoBuf.ProtoMember(46)]
        public double acceleration_error
        {
            get { return __pbn__acceleration_error.GetValueOrDefault(); }
            set { __pbn__acceleration_error = value; }
        }
        public bool ShouldSerializeacceleration_error()
        {
            return __pbn__acceleration_error != null;
        }
        public void Resetacceleration_error()
        {
            __pbn__acceleration_error = null;
        }
        private double? __pbn__acceleration_error;

        [global::ProtoBuf.ProtoMember(47)]
        public double jerk_reference
        {
            get { return __pbn__jerk_reference.GetValueOrDefault(); }
            set { __pbn__jerk_reference = value; }
        }
        public bool ShouldSerializejerk_reference()
        {
            return __pbn__jerk_reference != null;
        }
        public void Resetjerk_reference()
        {
            __pbn__jerk_reference = null;
        }
        private double? __pbn__jerk_reference;

        [global::ProtoBuf.ProtoMember(48)]
        public double jerk_feedback
        {
            get { return __pbn__jerk_feedback.GetValueOrDefault(); }
            set { __pbn__jerk_feedback = value; }
        }
        public bool ShouldSerializejerk_feedback()
        {
            return __pbn__jerk_feedback != null;
        }
        public void Resetjerk_feedback()
        {
            __pbn__jerk_feedback = null;
        }
        private double? __pbn__jerk_feedback;

        [global::ProtoBuf.ProtoMember(49)]
        public double jerk_error
        {
            get { return __pbn__jerk_error.GetValueOrDefault(); }
            set { __pbn__jerk_error = value; }
        }
        public bool ShouldSerializejerk_error()
        {
            return __pbn__jerk_error != null;
        }
        public void Resetjerk_error()
        {
            __pbn__jerk_error = null;
        }
        private double? __pbn__jerk_error;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InputDebug : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public InputDebug()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::apollo.common.Header localization_header { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::apollo.common.Header canbus_header { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::apollo.common.Header trajectory_header { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::apollo.common.Header latest_replan_trajectory_header { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Debug : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Debug()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public SimpleLongitudinalDebug simple_lon_debug { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public SimpleLateralDebug simple_lat_debug { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public InputDebug input_debug { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public SimpleMPCDebug simple_mpc_debug { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum TurnSignal
    {
        [global::ProtoBuf.ProtoEnum(Name = @"TURN_NONE")]
        TurnNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"TURN_LEFT")]
        TurnLeft = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"TURN_RIGHT")]
        TurnRight = 2,
    }

}

#pragma warning restore 0612, 1591, 3021
