// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/localization/proto/gps.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Apollo.Localization {

  /// <summary>Holder for reflection information generated from modules/localization/proto/gps.proto</summary>
  public static partial class GpsReflection {

    #region Descriptor
    /// <summary>File descriptor for modules/localization/proto/gps.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GpsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRtb2R1bGVzL2xvY2FsaXphdGlvbi9wcm90by9ncHMucHJvdG8SE2Fwb2xs",
            "by5sb2NhbGl6YXRpb24aIW1vZHVsZXMvY29tbW9uL3Byb3RvL2hlYWRlci5w",
            "cm90bxolbW9kdWxlcy9sb2NhbGl6YXRpb24vcHJvdG8vcG9zZS5wcm90byJd",
            "CgNHcHMSJQoGaGVhZGVyGAEgASgLMhUuYXBvbGxvLmNvbW1vbi5IZWFkZXIS",
            "LwoMbG9jYWxpemF0aW9uGAIgASgLMhkuYXBvbGxvLmxvY2FsaXphdGlvbi5Q",
            "b3NlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Apollo.Common.HeaderReflection.Descriptor, global::Apollo.Localization.PoseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Apollo.Localization.Gps), global::Apollo.Localization.Gps.Parser, new[]{ "Header", "Localization" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Gps : pb::IMessage<Gps> {
    private static readonly pb::MessageParser<Gps> _parser = new pb::MessageParser<Gps>(() => new Gps());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Gps> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Apollo.Localization.GpsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gps() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gps(Gps other) : this() {
      Header = other.header_ != null ? other.Header.Clone() : null;
      Localization = other.localization_ != null ? other.Localization.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Gps Clone() {
      return new Gps(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Apollo.Common.Header header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Apollo.Common.Header Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "localization" field.</summary>
    public const int LocalizationFieldNumber = 2;
    private global::Apollo.Localization.Pose localization_;
    /// <summary>
    /// Localization message: from GPS or localization
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Apollo.Localization.Pose Localization {
      get { return localization_; }
      set {
        localization_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Gps);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Gps other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (!object.Equals(Localization, other.Localization)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (localization_ != null) hash ^= Localization.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (localization_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Localization);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (localization_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Localization);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Gps other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          header_ = new global::Apollo.Common.Header();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.localization_ != null) {
        if (localization_ == null) {
          localization_ = new global::Apollo.Localization.Pose();
        }
        Localization.MergeFrom(other.Localization);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (header_ == null) {
              header_ = new global::Apollo.Common.Header();
            }
            input.ReadMessage(header_);
            break;
          }
          case 18: {
            if (localization_ == null) {
              localization_ = new global::Apollo.Localization.Pose();
            }
            input.ReadMessage(localization_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
