// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: pointcloud_preprocessor_config.proto

#pragma warning disable 0612, 1591, 3021
namespace apollo.perception.lidar
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PointCloudPreprocessorConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PointCloudPreprocessorConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool filter_naninf_points
        {
            get { return __pbn__filter_naninf_points ?? true; }
            set { __pbn__filter_naninf_points = value; }
        }
        public bool ShouldSerializefilter_naninf_points()
        {
            return __pbn__filter_naninf_points != null;
        }
        public void Resetfilter_naninf_points()
        {
            __pbn__filter_naninf_points = null;
        }
        private bool? __pbn__filter_naninf_points;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool filter_nearby_box_points
        {
            get { return __pbn__filter_nearby_box_points ?? false; }
            set { __pbn__filter_nearby_box_points = value; }
        }
        public bool ShouldSerializefilter_nearby_box_points()
        {
            return __pbn__filter_nearby_box_points != null;
        }
        public void Resetfilter_nearby_box_points()
        {
            __pbn__filter_nearby_box_points = null;
        }
        private bool? __pbn__filter_nearby_box_points;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(0f)]
        public float box_forward_x
        {
            get { return __pbn__box_forward_x ?? 0f; }
            set { __pbn__box_forward_x = value; }
        }
        public bool ShouldSerializebox_forward_x()
        {
            return __pbn__box_forward_x != null;
        }
        public void Resetbox_forward_x()
        {
            __pbn__box_forward_x = null;
        }
        private float? __pbn__box_forward_x;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(0f)]
        public float box_backward_x
        {
            get { return __pbn__box_backward_x ?? 0f; }
            set { __pbn__box_backward_x = value; }
        }
        public bool ShouldSerializebox_backward_x()
        {
            return __pbn__box_backward_x != null;
        }
        public void Resetbox_backward_x()
        {
            __pbn__box_backward_x = null;
        }
        private float? __pbn__box_backward_x;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue(0f)]
        public float box_forward_y
        {
            get { return __pbn__box_forward_y ?? 0f; }
            set { __pbn__box_forward_y = value; }
        }
        public bool ShouldSerializebox_forward_y()
        {
            return __pbn__box_forward_y != null;
        }
        public void Resetbox_forward_y()
        {
            __pbn__box_forward_y = null;
        }
        private float? __pbn__box_forward_y;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue(0f)]
        public float box_backward_y
        {
            get { return __pbn__box_backward_y ?? 0f; }
            set { __pbn__box_backward_y = value; }
        }
        public bool ShouldSerializebox_backward_y()
        {
            return __pbn__box_backward_y != null;
        }
        public void Resetbox_backward_y()
        {
            __pbn__box_backward_y = null;
        }
        private float? __pbn__box_backward_y;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool filter_high_z_points
        {
            get { return __pbn__filter_high_z_points ?? false; }
            set { __pbn__filter_high_z_points = value; }
        }
        public bool ShouldSerializefilter_high_z_points()
        {
            return __pbn__filter_high_z_points != null;
        }
        public void Resetfilter_high_z_points()
        {
            __pbn__filter_high_z_points = null;
        }
        private bool? __pbn__filter_high_z_points;

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue(5f)]
        public float z_threshold
        {
            get { return __pbn__z_threshold ?? 5f; }
            set { __pbn__z_threshold = value; }
        }
        public bool ShouldSerializez_threshold()
        {
            return __pbn__z_threshold != null;
        }
        public void Resetz_threshold()
        {
            __pbn__z_threshold = null;
        }
        private float? __pbn__z_threshold;

    }

}

#pragma warning restore 0612, 1591, 3021
