// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: navi_speed_decider_config.proto

#pragma warning disable 0612, 1591, 3021
namespace apollo.planning
{

    [global::ProtoBuf.ProtoContract()]
    public partial class NaviSpeedDeciderConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public NaviSpeedDeciderConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(2)]
        public double preferred_accel
        {
            get { return __pbn__preferred_accel ?? 2; }
            set { __pbn__preferred_accel = value; }
        }
        public bool ShouldSerializepreferred_accel()
        {
            return __pbn__preferred_accel != null;
        }
        public void Resetpreferred_accel()
        {
            __pbn__preferred_accel = null;
        }
        private double? __pbn__preferred_accel;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(2)]
        public double preferred_decel
        {
            get { return __pbn__preferred_decel ?? 2; }
            set { __pbn__preferred_decel = value; }
        }
        public bool ShouldSerializepreferred_decel()
        {
            return __pbn__preferred_decel != null;
        }
        public void Resetpreferred_decel()
        {
            __pbn__preferred_decel = null;
        }
        private double? __pbn__preferred_decel;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(2)]
        public double preferred_jerk
        {
            get { return __pbn__preferred_jerk ?? 2; }
            set { __pbn__preferred_jerk = value; }
        }
        public bool ShouldSerializepreferred_jerk()
        {
            return __pbn__preferred_jerk != null;
        }
        public void Resetpreferred_jerk()
        {
            __pbn__preferred_jerk = null;
        }
        private double? __pbn__preferred_jerk;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(4)]
        public double max_accel
        {
            get { return __pbn__max_accel ?? 4; }
            set { __pbn__max_accel = value; }
        }
        public bool ShouldSerializemax_accel()
        {
            return __pbn__max_accel != null;
        }
        public void Resetmax_accel()
        {
            __pbn__max_accel = null;
        }
        private double? __pbn__max_accel;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue(5)]
        public double max_decel
        {
            get { return __pbn__max_decel ?? 5; }
            set { __pbn__max_decel = value; }
        }
        public bool ShouldSerializemax_decel()
        {
            return __pbn__max_decel != null;
        }
        public void Resetmax_decel()
        {
            __pbn__max_decel = null;
        }
        private double? __pbn__max_decel;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue(0.5)]
        public double obstacle_buffer
        {
            get { return __pbn__obstacle_buffer ?? 0.5; }
            set { __pbn__obstacle_buffer = value; }
        }
        public bool ShouldSerializeobstacle_buffer()
        {
            return __pbn__obstacle_buffer != null;
        }
        public void Resetobstacle_buffer()
        {
            __pbn__obstacle_buffer = null;
        }
        private double? __pbn__obstacle_buffer;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue(2)]
        public double safe_distance_base
        {
            get { return __pbn__safe_distance_base ?? 2; }
            set { __pbn__safe_distance_base = value; }
        }
        public bool ShouldSerializesafe_distance_base()
        {
            return __pbn__safe_distance_base != null;
        }
        public void Resetsafe_distance_base()
        {
            __pbn__safe_distance_base = null;
        }
        private double? __pbn__safe_distance_base;

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue(1)]
        public double safe_distance_ratio
        {
            get { return __pbn__safe_distance_ratio ?? 1; }
            set { __pbn__safe_distance_ratio = value; }
        }
        public bool ShouldSerializesafe_distance_ratio()
        {
            return __pbn__safe_distance_ratio != null;
        }
        public void Resetsafe_distance_ratio()
        {
            __pbn__safe_distance_ratio = null;
        }
        private double? __pbn__safe_distance_ratio;

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue(0.5)]
        public double following_accel_ratio
        {
            get { return __pbn__following_accel_ratio ?? 0.5; }
            set { __pbn__following_accel_ratio = value; }
        }
        public bool ShouldSerializefollowing_accel_ratio()
        {
            return __pbn__following_accel_ratio != null;
        }
        public void Resetfollowing_accel_ratio()
        {
            __pbn__following_accel_ratio = null;
        }
        private double? __pbn__following_accel_ratio;

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue(1.2)]
        public double soft_centric_accel_limit
        {
            get { return __pbn__soft_centric_accel_limit ?? 1.2; }
            set { __pbn__soft_centric_accel_limit = value; }
        }
        public bool ShouldSerializesoft_centric_accel_limit()
        {
            return __pbn__soft_centric_accel_limit != null;
        }
        public void Resetsoft_centric_accel_limit()
        {
            __pbn__soft_centric_accel_limit = null;
        }
        private double? __pbn__soft_centric_accel_limit;

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue(1.5)]
        public double hard_centric_accel_limit
        {
            get { return __pbn__hard_centric_accel_limit ?? 1.5; }
            set { __pbn__hard_centric_accel_limit = value; }
        }
        public bool ShouldSerializehard_centric_accel_limit()
        {
            return __pbn__hard_centric_accel_limit != null;
        }
        public void Resethard_centric_accel_limit()
        {
            __pbn__hard_centric_accel_limit = null;
        }
        private double? __pbn__hard_centric_accel_limit;

        [global::ProtoBuf.ProtoMember(12)]
        [global::System.ComponentModel.DefaultValue(100)]
        public double hard_speed_limit
        {
            get { return __pbn__hard_speed_limit ?? 100; }
            set { __pbn__hard_speed_limit = value; }
        }
        public bool ShouldSerializehard_speed_limit()
        {
            return __pbn__hard_speed_limit != null;
        }
        public void Resethard_speed_limit()
        {
            __pbn__hard_speed_limit = null;
        }
        private double? __pbn__hard_speed_limit;

        [global::ProtoBuf.ProtoMember(13)]
        [global::System.ComponentModel.DefaultValue(10)]
        public double hard_accel_limit
        {
            get { return __pbn__hard_accel_limit ?? 10; }
            set { __pbn__hard_accel_limit = value; }
        }
        public bool ShouldSerializehard_accel_limit()
        {
            return __pbn__hard_accel_limit != null;
        }
        public void Resethard_accel_limit()
        {
            __pbn__hard_accel_limit = null;
        }
        private double? __pbn__hard_accel_limit;

        [global::ProtoBuf.ProtoMember(14)]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool enable_safe_path
        {
            get { return __pbn__enable_safe_path ?? true; }
            set { __pbn__enable_safe_path = value; }
        }
        public bool ShouldSerializeenable_safe_path()
        {
            return __pbn__enable_safe_path != null;
        }
        public void Resetenable_safe_path()
        {
            __pbn__enable_safe_path = null;
        }
        private bool? __pbn__enable_safe_path;

        [global::ProtoBuf.ProtoMember(15)]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool enable_planning_start_point
        {
            get { return __pbn__enable_planning_start_point ?? true; }
            set { __pbn__enable_planning_start_point = value; }
        }
        public bool ShouldSerializeenable_planning_start_point()
        {
            return __pbn__enable_planning_start_point != null;
        }
        public void Resetenable_planning_start_point()
        {
            __pbn__enable_planning_start_point = null;
        }
        private bool? __pbn__enable_planning_start_point;

        [global::ProtoBuf.ProtoMember(16)]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool enable_accel_auto_compensation
        {
            get { return __pbn__enable_accel_auto_compensation ?? true; }
            set { __pbn__enable_accel_auto_compensation = value; }
        }
        public bool ShouldSerializeenable_accel_auto_compensation()
        {
            return __pbn__enable_accel_auto_compensation != null;
        }
        public void Resetenable_accel_auto_compensation()
        {
            __pbn__enable_accel_auto_compensation = null;
        }
        private bool? __pbn__enable_accel_auto_compensation;

        [global::ProtoBuf.ProtoMember(17)]
        [global::System.ComponentModel.DefaultValue(0)]
        public double kappa_preview
        {
            get { return __pbn__kappa_preview ?? 0; }
            set { __pbn__kappa_preview = value; }
        }
        public bool ShouldSerializekappa_preview()
        {
            return __pbn__kappa_preview != null;
        }
        public void Resetkappa_preview()
        {
            __pbn__kappa_preview = null;
        }
        private double? __pbn__kappa_preview;

        [global::ProtoBuf.ProtoMember(18)]
        [global::System.ComponentModel.DefaultValue(0)]
        public double kappa_threshold
        {
            get { return __pbn__kappa_threshold ?? 0; }
            set { __pbn__kappa_threshold = value; }
        }
        public bool ShouldSerializekappa_threshold()
        {
            return __pbn__kappa_threshold != null;
        }
        public void Resetkappa_threshold()
        {
            __pbn__kappa_threshold = null;
        }
        private double? __pbn__kappa_threshold;

    }

}

#pragma warning restore 0612, 1591, 3021
