// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: planning.proto

#pragma warning disable 0612, 1591, 3021
namespace apollo.planning
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ADCSignals : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ADCSignals()
        {
            signal = new global::System.Collections.Generic.List<SignalType>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<SignalType> signal { get; private set; }

        [global::ProtoBuf.ProtoContract()]
        public enum SignalType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"LEFT_TURN")]
            LeftTurn = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"RIGHT_TURN")]
            RightTurn = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"LOW_BEAM_LIGHT")]
            LowBeamLight = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"HIGH_BEAM_LIGHT")]
            HighBeamLight = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"FOG_LIGHT")]
            FogLight = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"EMERGENCY_LIGHT")]
            EmergencyLight = 6,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EStop : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public EStop()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public bool is_estop
        {
            get { return __pbn__is_estop.GetValueOrDefault(); }
            set { __pbn__is_estop = value; }
        }
        public bool ShouldSerializeis_estop()
        {
            return __pbn__is_estop != null;
        }
        public void Resetis_estop()
        {
            __pbn__is_estop = null;
        }
        private bool? __pbn__is_estop;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string reason
        {
            get { return __pbn__reason ?? ""; }
            set { __pbn__reason = value; }
        }
        public bool ShouldSerializereason()
        {
            return __pbn__reason != null;
        }
        public void Resetreason()
        {
            __pbn__reason = null;
        }
        private string __pbn__reason;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TaskStats : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public TaskStats()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get { return __pbn__name ?? ""; }
            set { __pbn__name = value; }
        }
        public bool ShouldSerializename()
        {
            return __pbn__name != null;
        }
        public void Resetname()
        {
            __pbn__name = null;
        }
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(2)]
        public double time_ms
        {
            get { return __pbn__time_ms.GetValueOrDefault(); }
            set { __pbn__time_ms = value; }
        }
        public bool ShouldSerializetime_ms()
        {
            return __pbn__time_ms != null;
        }
        public void Resettime_ms()
        {
            __pbn__time_ms = null;
        }
        private double? __pbn__time_ms;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LatencyStats : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public LatencyStats()
        {
            task_stats = new global::System.Collections.Generic.List<TaskStats>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public double total_time_ms
        {
            get { return __pbn__total_time_ms.GetValueOrDefault(); }
            set { __pbn__total_time_ms = value; }
        }
        public bool ShouldSerializetotal_time_ms()
        {
            return __pbn__total_time_ms != null;
        }
        public void Resettotal_time_ms()
        {
            __pbn__total_time_ms = null;
        }
        private double? __pbn__total_time_ms;

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<TaskStats> task_stats { get; private set; }

        [global::ProtoBuf.ProtoMember(3)]
        public double init_frame_time_ms
        {
            get { return __pbn__init_frame_time_ms.GetValueOrDefault(); }
            set { __pbn__init_frame_time_ms = value; }
        }
        public bool ShouldSerializeinit_frame_time_ms()
        {
            return __pbn__init_frame_time_ms != null;
        }
        public void Resetinit_frame_time_ms()
        {
            __pbn__init_frame_time_ms = null;
        }
        private double? __pbn__init_frame_time_ms;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RSSInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RSSInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public bool is_rss_safe
        {
            get { return __pbn__is_rss_safe.GetValueOrDefault(); }
            set { __pbn__is_rss_safe = value; }
        }
        public bool ShouldSerializeis_rss_safe()
        {
            return __pbn__is_rss_safe != null;
        }
        public void Resetis_rss_safe()
        {
            __pbn__is_rss_safe = null;
        }
        private bool? __pbn__is_rss_safe;

        [global::ProtoBuf.ProtoMember(2)]
        public double cur_dist_lon
        {
            get { return __pbn__cur_dist_lon.GetValueOrDefault(); }
            set { __pbn__cur_dist_lon = value; }
        }
        public bool ShouldSerializecur_dist_lon()
        {
            return __pbn__cur_dist_lon != null;
        }
        public void Resetcur_dist_lon()
        {
            __pbn__cur_dist_lon = null;
        }
        private double? __pbn__cur_dist_lon;

        [global::ProtoBuf.ProtoMember(3)]
        public double rss_safe_dist_lon
        {
            get { return __pbn__rss_safe_dist_lon.GetValueOrDefault(); }
            set { __pbn__rss_safe_dist_lon = value; }
        }
        public bool ShouldSerializerss_safe_dist_lon()
        {
            return __pbn__rss_safe_dist_lon != null;
        }
        public void Resetrss_safe_dist_lon()
        {
            __pbn__rss_safe_dist_lon = null;
        }
        private double? __pbn__rss_safe_dist_lon;

        [global::ProtoBuf.ProtoMember(4)]
        public double acc_lon_range_minimum
        {
            get { return __pbn__acc_lon_range_minimum.GetValueOrDefault(); }
            set { __pbn__acc_lon_range_minimum = value; }
        }
        public bool ShouldSerializeacc_lon_range_minimum()
        {
            return __pbn__acc_lon_range_minimum != null;
        }
        public void Resetacc_lon_range_minimum()
        {
            __pbn__acc_lon_range_minimum = null;
        }
        private double? __pbn__acc_lon_range_minimum;

        [global::ProtoBuf.ProtoMember(5)]
        public double acc_lon_range_maximum
        {
            get { return __pbn__acc_lon_range_maximum.GetValueOrDefault(); }
            set { __pbn__acc_lon_range_maximum = value; }
        }
        public bool ShouldSerializeacc_lon_range_maximum()
        {
            return __pbn__acc_lon_range_maximum != null;
        }
        public void Resetacc_lon_range_maximum()
        {
            __pbn__acc_lon_range_maximum = null;
        }
        private double? __pbn__acc_lon_range_maximum;

        [global::ProtoBuf.ProtoMember(6)]
        public double acc_lat_left_range_minimum
        {
            get { return __pbn__acc_lat_left_range_minimum.GetValueOrDefault(); }
            set { __pbn__acc_lat_left_range_minimum = value; }
        }
        public bool ShouldSerializeacc_lat_left_range_minimum()
        {
            return __pbn__acc_lat_left_range_minimum != null;
        }
        public void Resetacc_lat_left_range_minimum()
        {
            __pbn__acc_lat_left_range_minimum = null;
        }
        private double? __pbn__acc_lat_left_range_minimum;

        [global::ProtoBuf.ProtoMember(7)]
        public double acc_lat_left_range_maximum
        {
            get { return __pbn__acc_lat_left_range_maximum.GetValueOrDefault(); }
            set { __pbn__acc_lat_left_range_maximum = value; }
        }
        public bool ShouldSerializeacc_lat_left_range_maximum()
        {
            return __pbn__acc_lat_left_range_maximum != null;
        }
        public void Resetacc_lat_left_range_maximum()
        {
            __pbn__acc_lat_left_range_maximum = null;
        }
        private double? __pbn__acc_lat_left_range_maximum;

        [global::ProtoBuf.ProtoMember(8)]
        public double acc_lat_right_range_minimum
        {
            get { return __pbn__acc_lat_right_range_minimum.GetValueOrDefault(); }
            set { __pbn__acc_lat_right_range_minimum = value; }
        }
        public bool ShouldSerializeacc_lat_right_range_minimum()
        {
            return __pbn__acc_lat_right_range_minimum != null;
        }
        public void Resetacc_lat_right_range_minimum()
        {
            __pbn__acc_lat_right_range_minimum = null;
        }
        private double? __pbn__acc_lat_right_range_minimum;

        [global::ProtoBuf.ProtoMember(9)]
        public double acc_lat_right_range_maximum
        {
            get { return __pbn__acc_lat_right_range_maximum.GetValueOrDefault(); }
            set { __pbn__acc_lat_right_range_maximum = value; }
        }
        public bool ShouldSerializeacc_lat_right_range_maximum()
        {
            return __pbn__acc_lat_right_range_maximum != null;
        }
        public void Resetacc_lat_right_range_maximum()
        {
            __pbn__acc_lat_right_range_maximum = null;
        }
        private double? __pbn__acc_lat_right_range_maximum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ADCTrajectory : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ADCTrajectory()
        {
            trajectory_point = new global::System.Collections.Generic.List<global::apollo.common.TrajectoryPoint>();
            path_point = new global::System.Collections.Generic.List<global::apollo.common.PathPoint>();
            lane_id = new global::System.Collections.Generic.List<global::apollo.hdmap.Id>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::apollo.common.Header header { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public double total_path_length
        {
            get { return __pbn__total_path_length.GetValueOrDefault(); }
            set { __pbn__total_path_length = value; }
        }
        public bool ShouldSerializetotal_path_length()
        {
            return __pbn__total_path_length != null;
        }
        public void Resettotal_path_length()
        {
            __pbn__total_path_length = null;
        }
        private double? __pbn__total_path_length;

        [global::ProtoBuf.ProtoMember(3)]
        public double total_path_time
        {
            get { return __pbn__total_path_time.GetValueOrDefault(); }
            set { __pbn__total_path_time = value; }
        }
        public bool ShouldSerializetotal_path_time()
        {
            return __pbn__total_path_time != null;
        }
        public void Resettotal_path_time()
        {
            __pbn__total_path_time = null;
        }
        private double? __pbn__total_path_time;

        [global::ProtoBuf.ProtoMember(12)]
        public global::System.Collections.Generic.List<global::apollo.common.TrajectoryPoint> trajectory_point { get; private set; }

        [global::ProtoBuf.ProtoMember(6)]
        public EStop estop { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public global::System.Collections.Generic.List<global::apollo.common.PathPoint> path_point { get; private set; }

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool is_replan
        {
            get { return __pbn__is_replan ?? false; }
            set { __pbn__is_replan = value; }
        }
        public bool ShouldSerializeis_replan()
        {
            return __pbn__is_replan != null;
        }
        public void Resetis_replan()
        {
            __pbn__is_replan = null;
        }
        private bool? __pbn__is_replan;

        [global::ProtoBuf.ProtoMember(22)]
        [global::System.ComponentModel.DefaultValue("")]
        public string replan_reason
        {
            get { return __pbn__replan_reason ?? ""; }
            set { __pbn__replan_reason = value; }
        }
        public bool ShouldSerializereplan_reason()
        {
            return __pbn__replan_reason != null;
        }
        public void Resetreplan_reason()
        {
            __pbn__replan_reason = null;
        }
        private string __pbn__replan_reason;

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue(global::apollo.canbus.Chassis.GearPosition.GearNeutral)]
        public global::apollo.canbus.Chassis.GearPosition gear
        {
            get { return __pbn__gear ?? global::apollo.canbus.Chassis.GearPosition.GearNeutral; }
            set { __pbn__gear = value; }
        }
        public bool ShouldSerializegear()
        {
            return __pbn__gear != null;
        }
        public void Resetgear()
        {
            __pbn__gear = null;
        }
        private global::apollo.canbus.Chassis.GearPosition? __pbn__gear;

        [global::ProtoBuf.ProtoMember(14)]
        public DecisionResult decision { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public LatencyStats latency_stats { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public global::apollo.common.Header routing_header { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public global::apollo.planning_internal.Debug debug { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        [global::System.ComponentModel.DefaultValue(RightOfWayStatus.Unprotected)]
        public RightOfWayStatus right_of_way_status
        {
            get { return __pbn__right_of_way_status ?? RightOfWayStatus.Unprotected; }
            set { __pbn__right_of_way_status = value; }
        }
        public bool ShouldSerializeright_of_way_status()
        {
            return __pbn__right_of_way_status != null;
        }
        public void Resetright_of_way_status()
        {
            __pbn__right_of_way_status = null;
        }
        private RightOfWayStatus? __pbn__right_of_way_status;

        [global::ProtoBuf.ProtoMember(18)]
        public global::System.Collections.Generic.List<global::apollo.hdmap.Id> lane_id { get; private set; }

        [global::ProtoBuf.ProtoMember(19)]
        public global::apollo.common.EngageAdvice engage_advice { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public CriticalRegion critical_region { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        [global::System.ComponentModel.DefaultValue(TrajectoryType.Unknown)]
        public TrajectoryType trajectory_type
        {
            get { return __pbn__trajectory_type ?? TrajectoryType.Unknown; }
            set { __pbn__trajectory_type = value; }
        }
        public bool ShouldSerializetrajectory_type()
        {
            return __pbn__trajectory_type != null;
        }
        public void Resettrajectory_type()
        {
            __pbn__trajectory_type = null;
        }
        private TrajectoryType? __pbn__trajectory_type;

        [global::ProtoBuf.ProtoMember(100)]
        public RSSInfo rss_info { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class CriticalRegion : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            }
            public CriticalRegion()
            {
                region = new global::System.Collections.Generic.List<global::apollo.common.Polygon>();
                OnConstructor();
            }

            partial void OnConstructor();

            [global::ProtoBuf.ProtoMember(1)]
            public global::System.Collections.Generic.List<global::apollo.common.Polygon> region { get; private set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum RightOfWayStatus
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNPROTECTED")]
            Unprotected = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"PROTECTED")]
            Protected = 1,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum TrajectoryType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
            Unknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"NORMAL")]
            Normal = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"PATH_FALLBACK")]
            PathFallback = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"SPEED_FALLBACK")]
            SpeedFallback = 3,
        }

    }

}

#pragma warning restore 0612, 1591, 3021
