// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: planning_config.proto
// </auto-generated>

#pragma warning disable 0612, 1591, 3021
namespace apollo.planning
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PathDeciderConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PathDeciderConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TaskConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public TaskConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(TaskType.DP_POLY_PATH_OPTIMIZER)]
        public TaskType task_type
        {
            get { return __pbn__task_type ?? TaskType.DP_POLY_PATH_OPTIMIZER; }
            set { __pbn__task_type = value; }
        }
        public bool ShouldSerializetask_type()
        {
            return __pbn__task_type != null;
        }
        public void Resettask_type()
        {
            __pbn__task_type = null;
        }
        private TaskType? __pbn__task_type;

        [global::ProtoBuf.ProtoMember(2)]
        public DpPolyPathConfig dp_poly_path_config
        {
            get { return __pbn__task_config.Is(2) ? ((DpPolyPathConfig)__pbn__task_config.Object) : default(DpPolyPathConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializedp_poly_path_config()
        {
            return __pbn__task_config.Is(2);
        }
        public void Resetdp_poly_path_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 2);
        }

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__task_config;

        [global::ProtoBuf.ProtoMember(3)]
        public DpStSpeedConfig dp_st_speed_config
        {
            get { return __pbn__task_config.Is(3) ? ((DpStSpeedConfig)__pbn__task_config.Object) : default(DpStSpeedConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializedp_st_speed_config()
        {
            return __pbn__task_config.Is(3);
        }
        public void Resetdp_st_speed_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 3);
        }

        [global::ProtoBuf.ProtoMember(4)]
        public QpSplinePathConfig qp_spline_path_config
        {
            get { return __pbn__task_config.Is(4) ? ((QpSplinePathConfig)__pbn__task_config.Object) : default(QpSplinePathConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializeqp_spline_path_config()
        {
            return __pbn__task_config.Is(4);
        }
        public void Resetqp_spline_path_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 4);
        }

        [global::ProtoBuf.ProtoMember(5)]
        public QpStSpeedConfig qp_st_speed_config
        {
            get { return __pbn__task_config.Is(5) ? ((QpStSpeedConfig)__pbn__task_config.Object) : default(QpStSpeedConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
        }
        public bool ShouldSerializeqp_st_speed_config()
        {
            return __pbn__task_config.Is(5);
        }
        public void Resetqp_st_speed_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 5);
        }

        [global::ProtoBuf.ProtoMember(7)]
        public PathDeciderConfig path_decider_config
        {
            get { return __pbn__task_config.Is(7) ? ((PathDeciderConfig)__pbn__task_config.Object) : default(PathDeciderConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(7, value); }
        }
        public bool ShouldSerializepath_decider_config()
        {
            return __pbn__task_config.Is(7);
        }
        public void Resetpath_decider_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 7);
        }

        [global::ProtoBuf.ProtoMember(8)]
        public ProceedWithCautionSpeedConfig proceed_with_caution_speed_config
        {
            get { return __pbn__task_config.Is(8) ? ((ProceedWithCautionSpeedConfig)__pbn__task_config.Object) : default(ProceedWithCautionSpeedConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(8, value); }
        }
        public bool ShouldSerializeproceed_with_caution_speed_config()
        {
            return __pbn__task_config.Is(8);
        }
        public void Resetproceed_with_caution_speed_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 8);
        }

        [global::ProtoBuf.ProtoMember(9)]
        public QpPiecewiseJerkPathConfig qp_piecewise_jerk_path_config
        {
            get { return __pbn__task_config.Is(9) ? ((QpPiecewiseJerkPathConfig)__pbn__task_config.Object) : default(QpPiecewiseJerkPathConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(9, value); }
        }
        public bool ShouldSerializeqp_piecewise_jerk_path_config()
        {
            return __pbn__task_config.Is(9);
        }
        public void Resetqp_piecewise_jerk_path_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 9);
        }

        [global::ProtoBuf.ProtoMember(10)]
        public DeciderCreepConfig decider_creep_config
        {
            get { return __pbn__task_config.Is(10) ? ((DeciderCreepConfig)__pbn__task_config.Object) : default(DeciderCreepConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(10, value); }
        }
        public bool ShouldSerializedecider_creep_config()
        {
            return __pbn__task_config.Is(10);
        }
        public void Resetdecider_creep_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 10);
        }

        [global::ProtoBuf.ProtoMember(11)]
        public DeciderRuleBasedStopConfig decider_rule_based_stop_config
        {
            get { return __pbn__task_config.Is(11) ? ((DeciderRuleBasedStopConfig)__pbn__task_config.Object) : default(DeciderRuleBasedStopConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(11, value); }
        }
        public bool ShouldSerializedecider_rule_based_stop_config()
        {
            return __pbn__task_config.Is(11);
        }
        public void Resetdecider_rule_based_stop_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 11);
        }

        [global::ProtoBuf.ProtoMember(12)]
        public SidePassSafetyConfig side_pass_safety_config
        {
            get { return __pbn__task_config.Is(12) ? ((SidePassSafetyConfig)__pbn__task_config.Object) : default(SidePassSafetyConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(12, value); }
        }
        public bool ShouldSerializeside_pass_safety_config()
        {
            return __pbn__task_config.Is(12);
        }
        public void Resetside_pass_safety_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 12);
        }

        [global::ProtoBuf.ProtoMember(13)]
        public SidePassPathDeciderConfig side_pass_path_decider_config
        {
            get { return __pbn__task_config.Is(13) ? ((SidePassPathDeciderConfig)__pbn__task_config.Object) : default(SidePassPathDeciderConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(13, value); }
        }
        public bool ShouldSerializeside_pass_path_decider_config()
        {
            return __pbn__task_config.Is(13);
        }
        public void Resetside_pass_path_decider_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 13);
        }

        [global::ProtoBuf.ProtoMember(15)]
        public SpeedBoundsDeciderConfig speed_bounds_decider_config
        {
            get { return __pbn__task_config.Is(15) ? ((SpeedBoundsDeciderConfig)__pbn__task_config.Object) : default(SpeedBoundsDeciderConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(15, value); }
        }
        public bool ShouldSerializespeed_bounds_decider_config()
        {
            return __pbn__task_config.Is(15);
        }
        public void Resetspeed_bounds_decider_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 15);
        }

        [global::ProtoBuf.ProtoMember(16)]
        public PiecewiseJerkPathConfig piecewise_jerk_path_config
        {
            get { return __pbn__task_config.Is(16) ? ((PiecewiseJerkPathConfig)__pbn__task_config.Object) : default(PiecewiseJerkPathConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(16, value); }
        }
        public bool ShouldSerializepiecewise_jerk_path_config()
        {
            return __pbn__task_config.Is(16);
        }
        public void Resetpiecewise_jerk_path_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 16);
        }

        [global::ProtoBuf.ProtoMember(17)]
        public PathBoundDeciderConfig path_bound_decider_config
        {
            get { return __pbn__task_config.Is(17) ? ((PathBoundDeciderConfig)__pbn__task_config.Object) : default(PathBoundDeciderConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(17, value); }
        }
        public bool ShouldSerializepath_bound_decider_config()
        {
            return __pbn__task_config.Is(17);
        }
        public void Resetpath_bound_decider_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 17);
        }

        [global::ProtoBuf.ProtoMember(18)]
        public OpenSpaceFallBackDeciderConfig open_space_fallback_decider_config
        {
            get { return __pbn__task_config.Is(18) ? ((OpenSpaceFallBackDeciderConfig)__pbn__task_config.Object) : default(OpenSpaceFallBackDeciderConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(18, value); }
        }
        public bool ShouldSerializeopen_space_fallback_decider_config()
        {
            return __pbn__task_config.Is(18);
        }
        public void Resetopen_space_fallback_decider_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 18);
        }

        [global::ProtoBuf.ProtoMember(19)]
        public OpenSpaceRoiDeciderConfig open_space_roi_decider_config
        {
            get { return __pbn__task_config.Is(19) ? ((OpenSpaceRoiDeciderConfig)__pbn__task_config.Object) : default(OpenSpaceRoiDeciderConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(19, value); }
        }
        public bool ShouldSerializeopen_space_roi_decider_config()
        {
            return __pbn__task_config.Is(19);
        }
        public void Resetopen_space_roi_decider_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 19);
        }

        [global::ProtoBuf.ProtoMember(20)]
        public OpenSpaceTrajectoryProviderConfig open_space_trajectory_provider_config
        {
            get { return __pbn__task_config.Is(20) ? ((OpenSpaceTrajectoryProviderConfig)__pbn__task_config.Object) : default(OpenSpaceTrajectoryProviderConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(20, value); }
        }
        public bool ShouldSerializeopen_space_trajectory_provider_config()
        {
            return __pbn__task_config.Is(20);
        }
        public void Resetopen_space_trajectory_provider_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 20);
        }

        [global::ProtoBuf.ProtoMember(21)]
        public OpenSpaceTrajectoryPartitionConfig open_space_trajectory_partition_config
        {
            get { return __pbn__task_config.Is(21) ? ((OpenSpaceTrajectoryPartitionConfig)__pbn__task_config.Object) : default(OpenSpaceTrajectoryPartitionConfig); }
            set { __pbn__task_config = new global::ProtoBuf.DiscriminatedUnionObject(21, value); }
        }
        public bool ShouldSerializeopen_space_trajectory_partition_config()
        {
            return __pbn__task_config.Is(21);
        }
        public void Resetopen_space_trajectory_partition_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__task_config, 21);
        }

        [global::ProtoBuf.ProtoContract()]
        public enum TaskType
        {
            DP_POLY_PATH_OPTIMIZER = 0,
            DP_ST_SPEED_OPTIMIZER = 1,
            QP_SPLINE_PATH_OPTIMIZER = 2,
            QP_SPLINE_ST_SPEED_OPTIMIZER = 3,
            PATH_DECIDER = 4,
            SPEED_DECIDER = 5,
            POLY_ST_SPEED_OPTIMIZER = 6,
            NAVI_PATH_DECIDER = 7,
            NAVI_SPEED_DECIDER = 8,
            NAVI_OBSTACLE_DECIDER = 9,
            QP_PIECEWISE_JERK_PATH_OPTIMIZER = 10,
            DECIDER_CREEP = 11,
            DECIDER_RULE_BASED_STOP = 12,
            SIDE_PASS_PATH_DECIDER = 13,
            SIDE_PASS_SAFETY = 14,
            PROCEED_WITH_CAUTION_SPEED = 15,
            DECIDER_RSS = 16,
            SPEED_BOUNDS_PRIORI_DECIDER = 17,
            SPEED_BOUNDS_FINAL_DECIDER = 18,
            PIECEWISE_JERK_PATH_OPTIMIZER = 19,
            PATH_BOUND_DECIDER = 20,
            OPEN_SPACE_ROI_DECIDER = 21,
            OPEN_SPACE_TRAJECTORY_PROVIDER = 22,
            OPEN_SPACE_TRAJECTORY_PARTITION = 23,
            OPEN_SPACE_FALLBACK_DECIDER = 24,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScenarioLaneFollowConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ScenarioLaneFollowConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScenarioSidePassConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ScenarioSidePassConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(10)]
        public double side_pass_exit_distance
        {
            get { return __pbn__side_pass_exit_distance ?? 10; }
            set { __pbn__side_pass_exit_distance = value; }
        }
        public bool ShouldSerializeside_pass_exit_distance()
        {
            return __pbn__side_pass_exit_distance != null;
        }
        public void Resetside_pass_exit_distance()
        {
            __pbn__side_pass_exit_distance = null;
        }
        private double? __pbn__side_pass_exit_distance;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(1e-05)]
        public double approach_obstacle_max_stop_speed
        {
            get { return __pbn__approach_obstacle_max_stop_speed ?? 1e-05; }
            set { __pbn__approach_obstacle_max_stop_speed = value; }
        }
        public bool ShouldSerializeapproach_obstacle_max_stop_speed()
        {
            return __pbn__approach_obstacle_max_stop_speed != null;
        }
        public void Resetapproach_obstacle_max_stop_speed()
        {
            __pbn__approach_obstacle_max_stop_speed = null;
        }
        private double? __pbn__approach_obstacle_max_stop_speed;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(4)]
        public double approach_obstacle_min_stop_distance
        {
            get { return __pbn__approach_obstacle_min_stop_distance ?? 4; }
            set { __pbn__approach_obstacle_min_stop_distance = value; }
        }
        public bool ShouldSerializeapproach_obstacle_min_stop_distance()
        {
            return __pbn__approach_obstacle_min_stop_distance != null;
        }
        public void Resetapproach_obstacle_min_stop_distance()
        {
            __pbn__approach_obstacle_min_stop_distance = null;
        }
        private double? __pbn__approach_obstacle_min_stop_distance;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(0.1)]
        public double block_obstacle_min_speed
        {
            get { return __pbn__block_obstacle_min_speed ?? 0.1; }
            set { __pbn__block_obstacle_min_speed = value; }
        }
        public bool ShouldSerializeblock_obstacle_min_speed()
        {
            return __pbn__block_obstacle_min_speed != null;
        }
        public void Resetblock_obstacle_min_speed()
        {
            __pbn__block_obstacle_min_speed = null;
        }
        private double? __pbn__block_obstacle_min_speed;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool enable_obstacle_blocked_check
        {
            get { return __pbn__enable_obstacle_blocked_check ?? true; }
            set { __pbn__enable_obstacle_blocked_check = value; }
        }
        public bool ShouldSerializeenable_obstacle_blocked_check()
        {
            return __pbn__enable_obstacle_blocked_check != null;
        }
        public void Resetenable_obstacle_blocked_check()
        {
            __pbn__enable_obstacle_blocked_check = null;
        }
        private bool? __pbn__enable_obstacle_blocked_check;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue(30)]
        public uint max_backup_stage_cycle_num
        {
            get { return __pbn__max_backup_stage_cycle_num ?? 30; }
            set { __pbn__max_backup_stage_cycle_num = value; }
        }
        public bool ShouldSerializemax_backup_stage_cycle_num()
        {
            return __pbn__max_backup_stage_cycle_num != null;
        }
        public void Resetmax_backup_stage_cycle_num()
        {
            __pbn__max_backup_stage_cycle_num = null;
        }
        private uint? __pbn__max_backup_stage_cycle_num;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue(0.5)]
        public double min_l_nudge_buffer
        {
            get { return __pbn__min_l_nudge_buffer ?? 0.5; }
            set { __pbn__min_l_nudge_buffer = value; }
        }
        public bool ShouldSerializemin_l_nudge_buffer()
        {
            return __pbn__min_l_nudge_buffer != null;
        }
        public void Resetmin_l_nudge_buffer()
        {
            __pbn__min_l_nudge_buffer = null;
        }
        private double? __pbn__min_l_nudge_buffer;

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue(0.5)]
        public double min_front_obstacle_distance
        {
            get { return __pbn__min_front_obstacle_distance ?? 0.5; }
            set { __pbn__min_front_obstacle_distance = value; }
        }
        public bool ShouldSerializemin_front_obstacle_distance()
        {
            return __pbn__min_front_obstacle_distance != null;
        }
        public void Resetmin_front_obstacle_distance()
        {
            __pbn__min_front_obstacle_distance = null;
        }
        private double? __pbn__min_front_obstacle_distance;

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue(15)]
        public double max_front_obstacle_distance
        {
            get { return __pbn__max_front_obstacle_distance ?? 15; }
            set { __pbn__max_front_obstacle_distance = value; }
        }
        public bool ShouldSerializemax_front_obstacle_distance()
        {
            return __pbn__max_front_obstacle_distance != null;
        }
        public void Resetmax_front_obstacle_distance()
        {
            __pbn__max_front_obstacle_distance = null;
        }
        private double? __pbn__max_front_obstacle_distance;

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue(6)]
        public double stop_fence_distance_to_blocking_obstacle
        {
            get { return __pbn__stop_fence_distance_to_blocking_obstacle ?? 6; }
            set { __pbn__stop_fence_distance_to_blocking_obstacle = value; }
        }
        public bool ShouldSerializestop_fence_distance_to_blocking_obstacle()
        {
            return __pbn__stop_fence_distance_to_blocking_obstacle != null;
        }
        public void Resetstop_fence_distance_to_blocking_obstacle()
        {
            __pbn__stop_fence_distance_to_blocking_obstacle = null;
        }
        private double? __pbn__stop_fence_distance_to_blocking_obstacle;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScenarioBareIntersectionUnprotectedConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ScenarioBareIntersectionUnprotectedConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(40)]
        public double start_bare_intersection_scenario_distance
        {
            get { return __pbn__start_bare_intersection_scenario_distance ?? 40; }
            set { __pbn__start_bare_intersection_scenario_distance = value; }
        }
        public bool ShouldSerializestart_bare_intersection_scenario_distance()
        {
            return __pbn__start_bare_intersection_scenario_distance != null;
        }
        public void Resetstart_bare_intersection_scenario_distance()
        {
            __pbn__start_bare_intersection_scenario_distance = null;
        }
        private double? __pbn__start_bare_intersection_scenario_distance;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(3)]
        public double min_pass_s_distance
        {
            get { return __pbn__min_pass_s_distance ?? 3; }
            set { __pbn__min_pass_s_distance = value; }
        }
        public bool ShouldSerializemin_pass_s_distance()
        {
            return __pbn__min_pass_s_distance != null;
        }
        public void Resetmin_pass_s_distance()
        {
            __pbn__min_pass_s_distance = null;
        }
        private double? __pbn__min_pass_s_distance;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(8f)]
        public float stop_timeout_sec
        {
            get { return __pbn__stop_timeout_sec ?? 8f; }
            set { __pbn__stop_timeout_sec = value; }
        }
        public bool ShouldSerializestop_timeout_sec()
        {
            return __pbn__stop_timeout_sec != null;
        }
        public void Resetstop_timeout_sec()
        {
            __pbn__stop_timeout_sec = null;
        }
        private float? __pbn__stop_timeout_sec;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(10f)]
        public float creep_timeout_sec
        {
            get { return __pbn__creep_timeout_sec ?? 10f; }
            set { __pbn__creep_timeout_sec = value; }
        }
        public bool ShouldSerializecreep_timeout_sec()
        {
            return __pbn__creep_timeout_sec != null;
        }
        public void Resetcreep_timeout_sec()
        {
            __pbn__creep_timeout_sec = null;
        }
        private float? __pbn__creep_timeout_sec;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScenarioStopSignUnprotectedConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ScenarioStopSignUnprotectedConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(5)]
        public double start_stop_sign_scenario_distance
        {
            get { return __pbn__start_stop_sign_scenario_distance ?? 5; }
            set { __pbn__start_stop_sign_scenario_distance = value; }
        }
        public bool ShouldSerializestart_stop_sign_scenario_distance()
        {
            return __pbn__start_stop_sign_scenario_distance != null;
        }
        public void Resetstart_stop_sign_scenario_distance()
        {
            __pbn__start_stop_sign_scenario_distance = null;
        }
        private double? __pbn__start_stop_sign_scenario_distance;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(5)]
        public double watch_vehicle_max_valid_stop_distance
        {
            get { return __pbn__watch_vehicle_max_valid_stop_distance ?? 5; }
            set { __pbn__watch_vehicle_max_valid_stop_distance = value; }
        }
        public bool ShouldSerializewatch_vehicle_max_valid_stop_distance()
        {
            return __pbn__watch_vehicle_max_valid_stop_distance != null;
        }
        public void Resetwatch_vehicle_max_valid_stop_distance()
        {
            __pbn__watch_vehicle_max_valid_stop_distance = null;
        }
        private double? __pbn__watch_vehicle_max_valid_stop_distance;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(3.5)]
        public double max_valid_stop_distance
        {
            get { return __pbn__max_valid_stop_distance ?? 3.5; }
            set { __pbn__max_valid_stop_distance = value; }
        }
        public bool ShouldSerializemax_valid_stop_distance()
        {
            return __pbn__max_valid_stop_distance != null;
        }
        public void Resetmax_valid_stop_distance()
        {
            __pbn__max_valid_stop_distance = null;
        }
        private double? __pbn__max_valid_stop_distance;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(0.3)]
        public double max_adc_stop_speed
        {
            get { return __pbn__max_adc_stop_speed ?? 0.3; }
            set { __pbn__max_adc_stop_speed = value; }
        }
        public bool ShouldSerializemax_adc_stop_speed()
        {
            return __pbn__max_adc_stop_speed != null;
        }
        public void Resetmax_adc_stop_speed()
        {
            __pbn__max_adc_stop_speed = null;
        }
        private double? __pbn__max_adc_stop_speed;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue(1f)]
        public float stop_duration_sec
        {
            get { return __pbn__stop_duration_sec ?? 1f; }
            set { __pbn__stop_duration_sec = value; }
        }
        public bool ShouldSerializestop_duration_sec()
        {
            return __pbn__stop_duration_sec != null;
        }
        public void Resetstop_duration_sec()
        {
            __pbn__stop_duration_sec = null;
        }
        private float? __pbn__stop_duration_sec;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue(3)]
        public double min_pass_s_distance
        {
            get { return __pbn__min_pass_s_distance ?? 3; }
            set { __pbn__min_pass_s_distance = value; }
        }
        public bool ShouldSerializemin_pass_s_distance()
        {
            return __pbn__min_pass_s_distance != null;
        }
        public void Resetmin_pass_s_distance()
        {
            __pbn__min_pass_s_distance = null;
        }
        private double? __pbn__min_pass_s_distance;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue(8f)]
        public float stop_timeout_sec
        {
            get { return __pbn__stop_timeout_sec ?? 8f; }
            set { __pbn__stop_timeout_sec = value; }
        }
        public bool ShouldSerializestop_timeout_sec()
        {
            return __pbn__stop_timeout_sec != null;
        }
        public void Resetstop_timeout_sec()
        {
            __pbn__stop_timeout_sec = null;
        }
        private float? __pbn__stop_timeout_sec;

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue(10f)]
        public float creep_timeout_sec
        {
            get { return __pbn__creep_timeout_sec ?? 10f; }
            set { __pbn__creep_timeout_sec = value; }
        }
        public bool ShouldSerializecreep_timeout_sec()
        {
            return __pbn__creep_timeout_sec != null;
        }
        public void Resetcreep_timeout_sec()
        {
            __pbn__creep_timeout_sec = null;
        }
        private float? __pbn__creep_timeout_sec;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScenarioTrafficLightProtectedConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ScenarioTrafficLightProtectedConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(5)]
        public double start_traffic_light_scenario_distance
        {
            get { return __pbn__start_traffic_light_scenario_distance ?? 5; }
            set { __pbn__start_traffic_light_scenario_distance = value; }
        }
        public bool ShouldSerializestart_traffic_light_scenario_distance()
        {
            return __pbn__start_traffic_light_scenario_distance != null;
        }
        public void Resetstart_traffic_light_scenario_distance()
        {
            __pbn__start_traffic_light_scenario_distance = null;
        }
        private double? __pbn__start_traffic_light_scenario_distance;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(2)]
        public double max_valid_stop_distance
        {
            get { return __pbn__max_valid_stop_distance ?? 2; }
            set { __pbn__max_valid_stop_distance = value; }
        }
        public bool ShouldSerializemax_valid_stop_distance()
        {
            return __pbn__max_valid_stop_distance != null;
        }
        public void Resetmax_valid_stop_distance()
        {
            __pbn__max_valid_stop_distance = null;
        }
        private double? __pbn__max_valid_stop_distance;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(0.3)]
        public double max_adc_stop_speed
        {
            get { return __pbn__max_adc_stop_speed ?? 0.3; }
            set { __pbn__max_adc_stop_speed = value; }
        }
        public bool ShouldSerializemax_adc_stop_speed()
        {
            return __pbn__max_adc_stop_speed != null;
        }
        public void Resetmax_adc_stop_speed()
        {
            __pbn__max_adc_stop_speed = null;
        }
        private double? __pbn__max_adc_stop_speed;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(3)]
        public double min_pass_s_distance
        {
            get { return __pbn__min_pass_s_distance ?? 3; }
            set { __pbn__min_pass_s_distance = value; }
        }
        public bool ShouldSerializemin_pass_s_distance()
        {
            return __pbn__min_pass_s_distance != null;
        }
        public void Resetmin_pass_s_distance()
        {
            __pbn__min_pass_s_distance = null;
        }
        private double? __pbn__min_pass_s_distance;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScenarioTrafficLightUnprotectedLeftTurnConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ScenarioTrafficLightUnprotectedLeftTurnConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(5)]
        public double start_traffic_light_scenario_distance
        {
            get { return __pbn__start_traffic_light_scenario_distance ?? 5; }
            set { __pbn__start_traffic_light_scenario_distance = value; }
        }
        public bool ShouldSerializestart_traffic_light_scenario_distance()
        {
            return __pbn__start_traffic_light_scenario_distance != null;
        }
        public void Resetstart_traffic_light_scenario_distance()
        {
            __pbn__start_traffic_light_scenario_distance = null;
        }
        private double? __pbn__start_traffic_light_scenario_distance;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(3.5)]
        public double max_valid_stop_distance
        {
            get { return __pbn__max_valid_stop_distance ?? 3.5; }
            set { __pbn__max_valid_stop_distance = value; }
        }
        public bool ShouldSerializemax_valid_stop_distance()
        {
            return __pbn__max_valid_stop_distance != null;
        }
        public void Resetmax_valid_stop_distance()
        {
            __pbn__max_valid_stop_distance = null;
        }
        private double? __pbn__max_valid_stop_distance;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(0.3)]
        public double max_adc_stop_speed
        {
            get { return __pbn__max_adc_stop_speed ?? 0.3; }
            set { __pbn__max_adc_stop_speed = value; }
        }
        public bool ShouldSerializemax_adc_stop_speed()
        {
            return __pbn__max_adc_stop_speed != null;
        }
        public void Resetmax_adc_stop_speed()
        {
            __pbn__max_adc_stop_speed = null;
        }
        private double? __pbn__max_adc_stop_speed;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(3)]
        public double min_pass_s_distance
        {
            get { return __pbn__min_pass_s_distance ?? 3; }
            set { __pbn__min_pass_s_distance = value; }
        }
        public bool ShouldSerializemin_pass_s_distance()
        {
            return __pbn__min_pass_s_distance != null;
        }
        public void Resetmin_pass_s_distance()
        {
            __pbn__min_pass_s_distance = null;
        }
        private double? __pbn__min_pass_s_distance;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue(10f)]
        public float creep_timeout_sec
        {
            get { return __pbn__creep_timeout_sec ?? 10f; }
            set { __pbn__creep_timeout_sec = value; }
        }
        public bool ShouldSerializecreep_timeout_sec()
        {
            return __pbn__creep_timeout_sec != null;
        }
        public void Resetcreep_timeout_sec()
        {
            __pbn__creep_timeout_sec = null;
        }
        private float? __pbn__creep_timeout_sec;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScenarioTrafficLightUnprotectedRightTurnConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ScenarioTrafficLightUnprotectedRightTurnConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(5)]
        public double start_traffic_light_scenario_distance
        {
            get { return __pbn__start_traffic_light_scenario_distance ?? 5; }
            set { __pbn__start_traffic_light_scenario_distance = value; }
        }
        public bool ShouldSerializestart_traffic_light_scenario_distance()
        {
            return __pbn__start_traffic_light_scenario_distance != null;
        }
        public void Resetstart_traffic_light_scenario_distance()
        {
            __pbn__start_traffic_light_scenario_distance = null;
        }
        private double? __pbn__start_traffic_light_scenario_distance;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool enable_right_turn_on_red
        {
            get { return __pbn__enable_right_turn_on_red ?? false; }
            set { __pbn__enable_right_turn_on_red = value; }
        }
        public bool ShouldSerializeenable_right_turn_on_red()
        {
            return __pbn__enable_right_turn_on_red != null;
        }
        public void Resetenable_right_turn_on_red()
        {
            __pbn__enable_right_turn_on_red = null;
        }
        private bool? __pbn__enable_right_turn_on_red;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(3.5)]
        public double max_valid_stop_distance
        {
            get { return __pbn__max_valid_stop_distance ?? 3.5; }
            set { __pbn__max_valid_stop_distance = value; }
        }
        public bool ShouldSerializemax_valid_stop_distance()
        {
            return __pbn__max_valid_stop_distance != null;
        }
        public void Resetmax_valid_stop_distance()
        {
            __pbn__max_valid_stop_distance = null;
        }
        private double? __pbn__max_valid_stop_distance;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(0.3)]
        public double max_adc_stop_speed
        {
            get { return __pbn__max_adc_stop_speed ?? 0.3; }
            set { __pbn__max_adc_stop_speed = value; }
        }
        public bool ShouldSerializemax_adc_stop_speed()
        {
            return __pbn__max_adc_stop_speed != null;
        }
        public void Resetmax_adc_stop_speed()
        {
            __pbn__max_adc_stop_speed = null;
        }
        private double? __pbn__max_adc_stop_speed;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue(3)]
        public double min_pass_s_distance
        {
            get { return __pbn__min_pass_s_distance ?? 3; }
            set { __pbn__min_pass_s_distance = value; }
        }
        public bool ShouldSerializemin_pass_s_distance()
        {
            return __pbn__min_pass_s_distance != null;
        }
        public void Resetmin_pass_s_distance()
        {
            __pbn__min_pass_s_distance = null;
        }
        private double? __pbn__min_pass_s_distance;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue(3f)]
        public float red_light_right_turn_stop_duration_sec
        {
            get { return __pbn__red_light_right_turn_stop_duration_sec ?? 3f; }
            set { __pbn__red_light_right_turn_stop_duration_sec = value; }
        }
        public bool ShouldSerializered_light_right_turn_stop_duration_sec()
        {
            return __pbn__red_light_right_turn_stop_duration_sec != null;
        }
        public void Resetred_light_right_turn_stop_duration_sec()
        {
            __pbn__red_light_right_turn_stop_duration_sec = null;
        }
        private float? __pbn__red_light_right_turn_stop_duration_sec;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue(10f)]
        public float creep_timeout_sec
        {
            get { return __pbn__creep_timeout_sec ?? 10f; }
            set { __pbn__creep_timeout_sec = value; }
        }
        public bool ShouldSerializecreep_timeout_sec()
        {
            return __pbn__creep_timeout_sec != null;
        }
        public void Resetcreep_timeout_sec()
        {
            __pbn__creep_timeout_sec = null;
        }
        private float? __pbn__creep_timeout_sec;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScenarioValetParkingConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ScenarioValetParkingConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(20)]
        public double parking_spot_range_to_start
        {
            get { return __pbn__parking_spot_range_to_start ?? 20; }
            set { __pbn__parking_spot_range_to_start = value; }
        }
        public bool ShouldSerializeparking_spot_range_to_start()
        {
            return __pbn__parking_spot_range_to_start != null;
        }
        public void Resetparking_spot_range_to_start()
        {
            __pbn__parking_spot_range_to_start = null;
        }
        private double? __pbn__parking_spot_range_to_start;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(1)]
        public double max_valid_stop_distance
        {
            get { return __pbn__max_valid_stop_distance ?? 1; }
            set { __pbn__max_valid_stop_distance = value; }
        }
        public bool ShouldSerializemax_valid_stop_distance()
        {
            return __pbn__max_valid_stop_distance != null;
        }
        public void Resetmax_valid_stop_distance()
        {
            __pbn__max_valid_stop_distance = null;
        }
        private double? __pbn__max_valid_stop_distance;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(0.1)]
        public double max_adc_stop_speed
        {
            get { return __pbn__max_adc_stop_speed ?? 0.1; }
            set { __pbn__max_adc_stop_speed = value; }
        }
        public bool ShouldSerializemax_adc_stop_speed()
        {
            return __pbn__max_adc_stop_speed != null;
        }
        public void Resetmax_adc_stop_speed()
        {
            __pbn__max_adc_stop_speed = null;
        }
        private double? __pbn__max_adc_stop_speed;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScenarioNarrowStreetUTurnConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ScenarioNarrowStreetUTurnConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScenarioConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ScenarioConfig()
        {
            stage_type = new global::System.Collections.Generic.List<StageType>();
            stage_config = new global::System.Collections.Generic.List<StageConfig>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(ScenarioType.LANE_FOLLOW)]
        public ScenarioType scenario_type
        {
            get { return __pbn__scenario_type ?? ScenarioType.LANE_FOLLOW; }
            set { __pbn__scenario_type = value; }
        }
        public bool ShouldSerializescenario_type()
        {
            return __pbn__scenario_type != null;
        }
        public void Resetscenario_type()
        {
            __pbn__scenario_type = null;
        }
        private ScenarioType? __pbn__scenario_type;

        [global::ProtoBuf.ProtoMember(2)]
        public ScenarioLaneFollowConfig lane_follow_config
        {
            get { return __pbn__scenario_config.Is(2) ? ((ScenarioLaneFollowConfig)__pbn__scenario_config.Object) : default(ScenarioLaneFollowConfig); }
            set { __pbn__scenario_config = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializelane_follow_config()
        {
            return __pbn__scenario_config.Is(2);
        }
        public void Resetlane_follow_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__scenario_config, 2);
        }

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__scenario_config;

        [global::ProtoBuf.ProtoMember(3)]
        public ScenarioSidePassConfig side_pass_config
        {
            get { return __pbn__scenario_config.Is(3) ? ((ScenarioSidePassConfig)__pbn__scenario_config.Object) : default(ScenarioSidePassConfig); }
            set { __pbn__scenario_config = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializeside_pass_config()
        {
            return __pbn__scenario_config.Is(3);
        }
        public void Resetside_pass_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__scenario_config, 3);
        }

        [global::ProtoBuf.ProtoMember(4)]
        public ScenarioBareIntersectionUnprotectedConfig bare_intersection_unprotected_config
        {
            get { return __pbn__scenario_config.Is(4) ? ((ScenarioBareIntersectionUnprotectedConfig)__pbn__scenario_config.Object) : default(ScenarioBareIntersectionUnprotectedConfig); }
            set { __pbn__scenario_config = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializebare_intersection_unprotected_config()
        {
            return __pbn__scenario_config.Is(4);
        }
        public void Resetbare_intersection_unprotected_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__scenario_config, 4);
        }

        [global::ProtoBuf.ProtoMember(5)]
        public ScenarioStopSignUnprotectedConfig stop_sign_unprotected_config
        {
            get { return __pbn__scenario_config.Is(5) ? ((ScenarioStopSignUnprotectedConfig)__pbn__scenario_config.Object) : default(ScenarioStopSignUnprotectedConfig); }
            set { __pbn__scenario_config = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
        }
        public bool ShouldSerializestop_sign_unprotected_config()
        {
            return __pbn__scenario_config.Is(5);
        }
        public void Resetstop_sign_unprotected_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__scenario_config, 5);
        }

        [global::ProtoBuf.ProtoMember(6)]
        public ScenarioTrafficLightProtectedConfig traffic_light_protected_config
        {
            get { return __pbn__scenario_config.Is(6) ? ((ScenarioTrafficLightProtectedConfig)__pbn__scenario_config.Object) : default(ScenarioTrafficLightProtectedConfig); }
            set { __pbn__scenario_config = new global::ProtoBuf.DiscriminatedUnionObject(6, value); }
        }
        public bool ShouldSerializetraffic_light_protected_config()
        {
            return __pbn__scenario_config.Is(6);
        }
        public void Resettraffic_light_protected_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__scenario_config, 6);
        }

        [global::ProtoBuf.ProtoMember(7)]
        public ScenarioTrafficLightUnprotectedRightTurnConfig traffic_light_unprotected_right_turn_config
        {
            get { return __pbn__scenario_config.Is(7) ? ((ScenarioTrafficLightUnprotectedRightTurnConfig)__pbn__scenario_config.Object) : default(ScenarioTrafficLightUnprotectedRightTurnConfig); }
            set { __pbn__scenario_config = new global::ProtoBuf.DiscriminatedUnionObject(7, value); }
        }
        public bool ShouldSerializetraffic_light_unprotected_right_turn_config()
        {
            return __pbn__scenario_config.Is(7);
        }
        public void Resettraffic_light_unprotected_right_turn_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__scenario_config, 7);
        }

        [global::ProtoBuf.ProtoMember(8)]
        public ScenarioTrafficLightUnprotectedLeftTurnConfig traffic_light_unprotected_left_turn_config
        {
            get { return __pbn__scenario_config.Is(8) ? ((ScenarioTrafficLightUnprotectedLeftTurnConfig)__pbn__scenario_config.Object) : default(ScenarioTrafficLightUnprotectedLeftTurnConfig); }
            set { __pbn__scenario_config = new global::ProtoBuf.DiscriminatedUnionObject(8, value); }
        }
        public bool ShouldSerializetraffic_light_unprotected_left_turn_config()
        {
            return __pbn__scenario_config.Is(8);
        }
        public void Resettraffic_light_unprotected_left_turn_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__scenario_config, 8);
        }

        [global::ProtoBuf.ProtoMember(9)]
        public ScenarioValetParkingConfig valet_parking_config
        {
            get { return __pbn__scenario_config.Is(9) ? ((ScenarioValetParkingConfig)__pbn__scenario_config.Object) : default(ScenarioValetParkingConfig); }
            set { __pbn__scenario_config = new global::ProtoBuf.DiscriminatedUnionObject(9, value); }
        }
        public bool ShouldSerializevalet_parking_config()
        {
            return __pbn__scenario_config.Is(9);
        }
        public void Resetvalet_parking_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__scenario_config, 9);
        }

        [global::ProtoBuf.ProtoMember(10)]
        public ScenarioNarrowStreetUTurnConfig narrow_street_u_turn_config
        {
            get { return __pbn__scenario_config.Is(10) ? ((ScenarioNarrowStreetUTurnConfig)__pbn__scenario_config.Object) : default(ScenarioNarrowStreetUTurnConfig); }
            set { __pbn__scenario_config = new global::ProtoBuf.DiscriminatedUnionObject(10, value); }
        }
        public bool ShouldSerializenarrow_street_u_turn_config()
        {
            return __pbn__scenario_config.Is(10);
        }
        public void Resetnarrow_street_u_turn_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__scenario_config, 10);
        }

        [global::ProtoBuf.ProtoMember(11)]
        public global::System.Collections.Generic.List<StageType> stage_type { get; private set; }

        [global::ProtoBuf.ProtoMember(12)]
        public global::System.Collections.Generic.List<StageConfig> stage_config { get; private set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class StageConfig : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            {
                return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
            }
            public StageConfig()
            {
                task_type = new global::System.Collections.Generic.List<TaskConfig.TaskType>();
                task_config = new global::System.Collections.Generic.List<TaskConfig>();
                OnConstructor();
            }

            partial void OnConstructor();

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue(ScenarioConfig.StageType.NO_STAGE)]
            public ScenarioConfig.StageType stage_type
            {
                get { return __pbn__stage_type ?? ScenarioConfig.StageType.NO_STAGE; }
                set { __pbn__stage_type = value; }
            }
            public bool ShouldSerializestage_type()
            {
                return __pbn__stage_type != null;
            }
            public void Resetstage_type()
            {
                __pbn__stage_type = null;
            }
            private ScenarioConfig.StageType? __pbn__stage_type;

            [global::ProtoBuf.ProtoMember(2)]
            [global::System.ComponentModel.DefaultValue(true)]
            public bool enabled
            {
                get { return __pbn__enabled ?? true; }
                set { __pbn__enabled = value; }
            }
            public bool ShouldSerializeenabled()
            {
                return __pbn__enabled != null;
            }
            public void Resetenabled()
            {
                __pbn__enabled = null;
            }
            private bool? __pbn__enabled;

            [global::ProtoBuf.ProtoMember(3)]
            public global::System.Collections.Generic.List<TaskConfig.TaskType> task_type { get; private set; }

            [global::ProtoBuf.ProtoMember(4)]
            public global::System.Collections.Generic.List<TaskConfig> task_config { get; private set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum ScenarioType
        {
            LANE_FOLLOW = 0,
            CHANGE_LANE = 1,
            SIDE_PASS = 2,
            BARE_INTERSECTION_UNPROTECTED = 3,
            STOP_SIGN_PROTECTED = 4,
            STOP_SIGN_UNPROTECTED = 5,
            TRAFFIC_LIGHT_PROTECTED = 6,
            TRAFFIC_LIGHT_UNPROTECTED_LEFT_TURN = 7,
            TRAFFIC_LIGHT_UNPROTECTED_RIGHT_TURN = 8,
            YIELD_SIGN_UNPROTECTED = 9,
            VALET_PARKING = 10,
            NARROW_STREET_U_TURN = 11,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum StageType
        {
            NO_STAGE = 0,
            LANE_FOLLOW_DEFAULT_STAGE = 1,
            SIDE_PASS_APPROACH_OBSTACLE = 100,
            SIDE_PASS_GENERATE_PATH = 101,
            SIDE_PASS_STOP_ON_WAITPOINT = 102,
            SIDE_PASS_DETECT_SAFETY = 103,
            SIDE_PASS_PASS_OBSTACLE = 104,
            SIDE_PASS_BACKUP = 105,
            BARE_INTERSECTION_UNPROTECTED_APPROACH = 200,
            BARE_INTERSECTION_UNPROTECTED_CREEP = 201,
            BARE_INTERSECTION_UNPROTECTED_INTERSECTION_CRUISE = 202,
            STOP_SIGN_UNPROTECTED_PRE_STOP = 300,
            STOP_SIGN_UNPROTECTED_STOP = 301,
            STOP_SIGN_UNPROTECTED_CREEP = 302,
            STOP_SIGN_UNPROTECTED_INTERSECTION_CRUISE = 303,
            TRAFFIC_LIGHT_PROTECTED_APPROACH = 400,
            TRAFFIC_LIGHT_PROTECTED_INTERSECTION_CRUISE = 401,
            TRAFFIC_LIGHT_UNPROTECTED_LEFT_TURN_CREEP = 410,
            TRAFFIC_LIGHT_UNPROTECTED_LEFT_TURN_INTERSECTION_CRUISE = 411,
            TRAFFIC_LIGHT_UNPROTECTED_RIGHT_TURN_STOP = 420,
            TRAFFIC_LIGHT_UNPROTECTED_RIGHT_TURN_CREEP = 421,
            TRAFFIC_LIGHT_UNPROTECTED_RIGHT_TURN_INTERSECTION_CRUISE = 422,
            VALET_PARKING_APPROACHING_PARKING_SPOT = 501,
            VALET_PARKING_PARKING = 502,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlannerPublicRoadConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PlannerPublicRoadConfig()
        {
            scenario_type = new global::System.Collections.Generic.List<ScenarioConfig.ScenarioType>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<ScenarioConfig.ScenarioType> scenario_type { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlannerNaviConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PlannerNaviConfig()
        {
            task = new global::System.Collections.Generic.List<TaskConfig.TaskType>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<TaskConfig.TaskType> task { get; private set; }

        [global::ProtoBuf.ProtoMember(2)]
        public NaviPathDeciderConfig navi_path_decider_config { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public NaviSpeedDeciderConfig navi_speed_decider_config { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public NaviObstacleDeciderConfig navi_obstacle_decider_config { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RtkPlanningConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RtkPlanningConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(PlannerType.RTK)]
        public PlannerType planner_type
        {
            get { return __pbn__planner_type ?? PlannerType.RTK; }
            set { __pbn__planner_type = value; }
        }
        public bool ShouldSerializeplanner_type()
        {
            return __pbn__planner_type != null;
        }
        public void Resetplanner_type()
        {
            __pbn__planner_type = null;
        }
        private PlannerType? __pbn__planner_type;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StandardPlanningConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public StandardPlanningConfig()
        {
            planner_type = new global::System.Collections.Generic.List<PlannerType>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<PlannerType> planner_type { get; private set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PlannerPublicRoadConfig planner_public_road_config { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NavigationPlanningConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public NavigationPlanningConfig()
        {
            planner_type = new global::System.Collections.Generic.List<PlannerType>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<PlannerType> planner_type { get; private set; }

        [global::ProtoBuf.ProtoMember(4)]
        public PlannerNaviConfig planner_navi_config { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OpenSpacePlanningConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public OpenSpacePlanningConfig()
        {
            planner_type = new global::System.Collections.Generic.List<PlannerType>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<PlannerType> planner_type { get; private set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PlannerOpenSpaceConfig planner_open_space_config { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlanningConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PlanningConfig()
        {
            default_task_config = new global::System.Collections.Generic.List<TaskConfig>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public RtkPlanningConfig rtk_planning_config
        {
            get { return __pbn__planning_config.Is(1) ? ((RtkPlanningConfig)__pbn__planning_config.Object) : default(RtkPlanningConfig); }
            set { __pbn__planning_config = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
        }
        public bool ShouldSerializertk_planning_config()
        {
            return __pbn__planning_config.Is(1);
        }
        public void Resetrtk_planning_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__planning_config, 1);
        }

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__planning_config;

        [global::ProtoBuf.ProtoMember(2)]
        public StandardPlanningConfig standard_planning_config
        {
            get { return __pbn__planning_config.Is(2) ? ((StandardPlanningConfig)__pbn__planning_config.Object) : default(StandardPlanningConfig); }
            set { __pbn__planning_config = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializestandard_planning_config()
        {
            return __pbn__planning_config.Is(2);
        }
        public void Resetstandard_planning_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__planning_config, 2);
        }

        [global::ProtoBuf.ProtoMember(3)]
        public NavigationPlanningConfig navigation_planning_config
        {
            get { return __pbn__planning_config.Is(3) ? ((NavigationPlanningConfig)__pbn__planning_config.Object) : default(NavigationPlanningConfig); }
            set { __pbn__planning_config = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializenavigation_planning_config()
        {
            return __pbn__planning_config.Is(3);
        }
        public void Resetnavigation_planning_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__planning_config, 3);
        }

        [global::ProtoBuf.ProtoMember(4)]
        public OpenSpacePlanningConfig open_space_planning_config
        {
            get { return __pbn__planning_config.Is(4) ? ((OpenSpacePlanningConfig)__pbn__planning_config.Object) : default(OpenSpacePlanningConfig); }
            set { __pbn__planning_config = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializeopen_space_planning_config()
        {
            return __pbn__planning_config.Is(4);
        }
        public void Resetopen_space_planning_config()
        {
            global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__planning_config, 4);
        }

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<TaskConfig> default_task_config { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum PlannerType
    {
        RTK = 0,
        PUBLIC_ROAD = 1,
        OPEN_SPACE = 2,
        NAVI = 3,
        LATTICE = 4,
    }

}

#pragma warning restore 0612, 1591, 3021
