// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: relative_map_config.proto

#pragma warning disable 0612, 1591, 3021
namespace apollo.relative_map
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MapGenerationParam : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MapGenerationParam()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(1.75)]
        public double default_left_width
        {
            get { return __pbn__default_left_width ?? 1.75; }
            set { __pbn__default_left_width = value; }
        }
        public bool ShouldSerializedefault_left_width()
        {
            return __pbn__default_left_width != null;
        }
        public void Resetdefault_left_width()
        {
            __pbn__default_left_width = null;
        }
        private double? __pbn__default_left_width;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(1.75)]
        public double default_right_width
        {
            get { return __pbn__default_right_width ?? 1.75; }
            set { __pbn__default_right_width = value; }
        }
        public bool ShouldSerializedefault_right_width()
        {
            return __pbn__default_right_width != null;
        }
        public void Resetdefault_right_width()
        {
            __pbn__default_right_width = null;
        }
        private double? __pbn__default_right_width;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(29.0576)]
        public double default_speed_limit
        {
            get { return __pbn__default_speed_limit ?? 29.0576; }
            set { __pbn__default_speed_limit = value; }
        }
        public bool ShouldSerializedefault_speed_limit()
        {
            return __pbn__default_speed_limit != null;
        }
        public void Resetdefault_speed_limit()
        {
            __pbn__default_speed_limit = null;
        }
        private double? __pbn__default_speed_limit;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NavigationLaneConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public NavigationLaneConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(0.5)]
        public double min_lane_marker_quality
        {
            get { return __pbn__min_lane_marker_quality ?? 0.5; }
            set { __pbn__min_lane_marker_quality = value; }
        }
        public bool ShouldSerializemin_lane_marker_quality()
        {
            return __pbn__min_lane_marker_quality != null;
        }
        public void Resetmin_lane_marker_quality()
        {
            __pbn__min_lane_marker_quality = null;
        }
        private double? __pbn__min_lane_marker_quality;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(LaneSource.Perception)]
        public LaneSource lane_source
        {
            get { return __pbn__lane_source ?? LaneSource.Perception; }
            set { __pbn__lane_source = value; }
        }
        public bool ShouldSerializelane_source()
        {
            return __pbn__lane_source != null;
        }
        public void Resetlane_source()
        {
            __pbn__lane_source = null;
        }
        private LaneSource? __pbn__lane_source;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(250)]
        public double max_len_from_navigation_line
        {
            get { return __pbn__max_len_from_navigation_line ?? 250; }
            set { __pbn__max_len_from_navigation_line = value; }
        }
        public bool ShouldSerializemax_len_from_navigation_line()
        {
            return __pbn__max_len_from_navigation_line != null;
        }
        public void Resetmax_len_from_navigation_line()
        {
            __pbn__max_len_from_navigation_line = null;
        }
        private double? __pbn__max_len_from_navigation_line;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(150)]
        public double min_len_for_navigation_lane
        {
            get { return __pbn__min_len_for_navigation_lane ?? 150; }
            set { __pbn__min_len_for_navigation_lane = value; }
        }
        public bool ShouldSerializemin_len_for_navigation_lane()
        {
            return __pbn__min_len_for_navigation_lane != null;
        }
        public void Resetmin_len_for_navigation_lane()
        {
            __pbn__min_len_for_navigation_lane = null;
        }
        private double? __pbn__min_len_for_navigation_lane;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue(250)]
        public double max_len_for_navigation_lane
        {
            get { return __pbn__max_len_for_navigation_lane ?? 250; }
            set { __pbn__max_len_for_navigation_lane = value; }
        }
        public bool ShouldSerializemax_len_for_navigation_lane()
        {
            return __pbn__max_len_for_navigation_lane != null;
        }
        public void Resetmax_len_for_navigation_lane()
        {
            __pbn__max_len_for_navigation_lane = null;
        }
        private double? __pbn__max_len_for_navigation_lane;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue(8)]
        public double ratio_navigation_lane_len_to_speed
        {
            get { return __pbn__ratio_navigation_lane_len_to_speed ?? 8; }
            set { __pbn__ratio_navigation_lane_len_to_speed = value; }
        }
        public bool ShouldSerializeratio_navigation_lane_len_to_speed()
        {
            return __pbn__ratio_navigation_lane_len_to_speed != null;
        }
        public void Resetratio_navigation_lane_len_to_speed()
        {
            __pbn__ratio_navigation_lane_len_to_speed = null;
        }
        private double? __pbn__ratio_navigation_lane_len_to_speed;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue(15)]
        public double max_distance_to_navigation_line
        {
            get { return __pbn__max_distance_to_navigation_line ?? 15; }
            set { __pbn__max_distance_to_navigation_line = value; }
        }
        public bool ShouldSerializemax_distance_to_navigation_line()
        {
            return __pbn__max_distance_to_navigation_line != null;
        }
        public void Resetmax_distance_to_navigation_line()
        {
            __pbn__max_distance_to_navigation_line = null;
        }
        private double? __pbn__max_distance_to_navigation_line;

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue(0.5)]
        public double min_view_range_to_use_lane_marker
        {
            get { return __pbn__min_view_range_to_use_lane_marker ?? 0.5; }
            set { __pbn__min_view_range_to_use_lane_marker = value; }
        }
        public bool ShouldSerializemin_view_range_to_use_lane_marker()
        {
            return __pbn__min_view_range_to_use_lane_marker != null;
        }
        public void Resetmin_view_range_to_use_lane_marker()
        {
            __pbn__min_view_range_to_use_lane_marker = null;
        }
        private double? __pbn__min_view_range_to_use_lane_marker;

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue(1.5)]
        public double min_lane_half_width
        {
            get { return __pbn__min_lane_half_width ?? 1.5; }
            set { __pbn__min_lane_half_width = value; }
        }
        public bool ShouldSerializemin_lane_half_width()
        {
            return __pbn__min_lane_half_width != null;
        }
        public void Resetmin_lane_half_width()
        {
            __pbn__min_lane_half_width = null;
        }
        private double? __pbn__min_lane_half_width;

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue(2)]
        public double max_lane_half_width
        {
            get { return __pbn__max_lane_half_width ?? 2; }
            set { __pbn__max_lane_half_width = value; }
        }
        public bool ShouldSerializemax_lane_half_width()
        {
            return __pbn__max_lane_half_width != null;
        }
        public void Resetmax_lane_half_width()
        {
            __pbn__max_lane_half_width = null;
        }
        private double? __pbn__max_lane_half_width;

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue(0.1)]
        public double lane_marker_weight
        {
            get { return __pbn__lane_marker_weight ?? 0.1; }
            set { __pbn__lane_marker_weight = value; }
        }
        public bool ShouldSerializelane_marker_weight()
        {
            return __pbn__lane_marker_weight != null;
        }
        public void Resetlane_marker_weight()
        {
            __pbn__lane_marker_weight = null;
        }
        private double? __pbn__lane_marker_weight;

        [global::ProtoBuf.ProtoContract()]
        public enum LaneSource
        {
            [global::ProtoBuf.ProtoEnum(Name = @"PERCEPTION")]
            Perception = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"OFFLINE_GENERATED")]
            OfflineGenerated = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RelativeMapConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RelativeMapConfig()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public MapGenerationParam map_param { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public NavigationLaneConfig navigation_lane { get; set; }

    }

}

#pragma warning restore 0612, 1591, 3021
