// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: darkSCNN_postprocessor.proto

#pragma warning disable 0612, 1591, 3021
namespace apollo.perception.camera.lane
{

    [global::ProtoBuf.ProtoContract()]
    public partial class DarkSCNNLanePostprocessorParam : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public DarkSCNNLanePostprocessorParam()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(640)]
        public uint lane_map_width
        {
            get { return __pbn__lane_map_width ?? 640; }
            set { __pbn__lane_map_width = value; }
        }
        public bool ShouldSerializelane_map_width()
        {
            return __pbn__lane_map_width != null;
        }
        public void Resetlane_map_width()
        {
            __pbn__lane_map_width = null;
        }
        private uint? __pbn__lane_map_width;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(480)]
        public uint lane_map_height
        {
            get { return __pbn__lane_map_height ?? 480; }
            set { __pbn__lane_map_height = value; }
        }
        public bool ShouldSerializelane_map_height()
        {
            return __pbn__lane_map_height != null;
        }
        public void Resetlane_map_height()
        {
            __pbn__lane_map_height = null;
        }
        private uint? __pbn__lane_map_height;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(768)]
        public uint roi_height
        {
            get { return __pbn__roi_height ?? 768; }
            set { __pbn__roi_height = value; }
        }
        public bool ShouldSerializeroi_height()
        {
            return __pbn__roi_height != null;
        }
        public void Resetroi_height()
        {
            __pbn__roi_height = null;
        }
        private uint? __pbn__roi_height;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(312)]
        public uint roi_start
        {
            get { return __pbn__roi_start ?? 312; }
            set { __pbn__roi_start = value; }
        }
        public bool ShouldSerializeroi_start()
        {
            return __pbn__roi_start != null;
        }
        public void Resetroi_start()
        {
            __pbn__roi_start = null;
        }
        private uint? __pbn__roi_start;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue(1920)]
        public uint roi_width
        {
            get { return __pbn__roi_width ?? 1920; }
            set { __pbn__roi_width = value; }
        }
        public bool ShouldSerializeroi_width()
        {
            return __pbn__roi_width != null;
        }
        public void Resetroi_width()
        {
            __pbn__roi_width = null;
        }
        private uint? __pbn__roi_width;

    }

}

#pragma warning restore 0612, 1591, 3021
